### ISSUE TITLE
Potential Programming Languages 

### ISSUE THREAD

**Issue by christianperez42** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#10]
Research the programing language we are going to use to make the website.
Due: 2/12/24

**Comment by RaquelQuinones** [comment]
I was doing some research for web creation and saw that React Native could be useful.  
> RN is a cross-platform app development framework, that can be used to develop web applications.

**Comment by rukitoyordan** [comment]
That sounds like a good idea @RaquelQuinones! Like how the professor mentioned, in any case things can be translated from one language to another. Try to  discuss this with the team and see what would be most convenient.

**Comment by christianperez42** [comment]
**Stack Tecnológico:**

1. **Node.js para el Backend**: Node.js es un entorno de ejecución de JavaScript que permite a los desarrolladores construir aplicaciones del lado del servidor de manera eficiente y escalable.

2. **Express.js como Framework Web**: Express.js es un framework minimalista y flexible para Node.js que simplifica el desarrollo de aplicaciones web y APIs.

3. **EJS como Motor de Plantillas**: EJS (Embedded JavaScript) es un motor de plantillas que permite incrustar código JavaScript dentro de archivos HTML para generar dinámicamente contenido web en el servidor.

4. **MySQL como Base de Datos Relacional**: MySQL es un sistema de gestión de bases de datos relacional de código abierto ampliamente utilizado en aplicaciones web.

5. **Tailwind CSS para Estilización**: Tailwind CSS es un framework de CSS utilitario que proporciona una forma eficiente y flexible de diseñar interfaces de usuario.

Al combinar Node.js, Express.js, EJS, MySQL y Tailwind CSS, los desarrolladores pueden construir aplicaciones web robustas y escalables con un backend eficiente, una base de datos confiable, un estilo moderno y una experiencia de usuario atractiva.

**Comment by christianperez42** [comment]
https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/70546091/33110738-f2aa-40a4-ab93-a149170920aa


Aquí hay un ejemplo de un landing page basado en el stack mencionado.

**Comment by rukitoyordan** [comment]
This is resolved, I agree with all of these programming languages, except MySQL. We already have someone from another team who is knowledgeable on being able to work on a Database for us using PostgreSQL for hosting. I'd suggest researching on that a bit further, seeing I will be using all these resolved issues from Website Creation to be a guideline for the other teams. 

Como siempre, si creen que la cantidad de tiempo no concuerda con la puntuacion, dejenos saber.
