### ISSUE TITLE
Create foster list page

### ISSUE THREAD

**Issue by rafa-quiles** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#100]
creation of a page in the website that lists the fosters registered in the system
parts of the task
- make the page
- add button on home page that brings you here
- make the page display the list of fosters

i don't have much experience in dealing with tings like this, so let me know if this should be split into smaller tasks

**Comment by rukitoyordan** [comment]
Hi @rafa-quiles, this can be split into more tasks if you'd like. I think it is a good idea, so make sure to try and assign other members of the team to help you as well!

**Comment by rafa-quiles** [comment]
this task is almost done, i have implemented the foster page. and I'm just waiting on the pull request
