### ISSUE TITLE
Milestone #2 Presentation Attribution - Web Management Team 📱

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#108]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Website Management team towards the proper documentation and development on the **_Milestone 2 Presentation_**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, March 8 2024** 🚨

**Comment by smbv** [comment]
Accomplishments: @Adriana-Isabel & @christianperez42 
Future Work: @smbv & @GiovanniMaysonet

**Comment by GiovanniMaysonet** [comment]
1.Changed and replaced the Persona section with the applications of the concept we've implemented thus far in the website management theme.

2.Added illustrations and text to the Future work done section in the documentation presentation.
