### ISSUE TITLE
IDE Research

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#11]
Conduct comprehensive research to identify the optimal  Integrated Development Environment (IDE) for the website development team working on the RUMAR Adoption Project website. Provide a detailed analysis of various IDE options, considering factors such as ease of use, compatibility with project requirements, collaboration features, and overall development efficiency.

If necessary, expand on findings and provide details, including example code, files, or links to pertinent documentation.

Tentative Due Date: 02/12/2024

**Comment by rukitoyordan** [comment]
Good afternoon @smbv! This seems like good initiative, however as long as everyone can work seamlessly, having the same IDE isn't that important. It will depend on the programming languages used and ease of access. (Avoid having IDEs that require users to pay memberships, fees, that kind of stuff)

**Comment by smbv** [comment]
**Detailed Analysis of Various IDE Options:**

**Visual Studio Code:**
- **Ease of Use:** Known for simplicity and a user-friendly interface. Versatile extensions enhance functionality for various languages and project needs.
- **Compatibility with Project Requirements:** Supports a wide range of programming languages. Integrated terminal and debugging tools enhance compatibility.
- **Collaboration Features:** Built-in Git integration facilitates seamless version control. Extensions like Live Share enable real-time collaboration.
- **Overall Development Efficiency:** Excellent code editing features, quick navigation, and efficient debugging tools contribute to overall development efficiency. Active community support ensures continuous improvement.
- [Download Visual Studio Code](https://code.visualstudio.com/download)

**IntelliJ IDEA:**
- **Ease of Use:** Known for intelligent code assistance. Initial learning curve, but substantial productivity gains for experienced developers.
- **Compatibility with Project Requirements:** Excellent support for Java and JVM-based languages. Robust set of plugins caters to various project requirements.
- **Collaboration Features:** Tools for team collaboration, integrated version control support, and code review features enhance collaboration and maintain code quality.
- **Overall Development Efficiency:** Advanced coding features, powerful debugging tools, and a comprehensive set of development tools enhance overall efficiency for Java-based projects.
- [Download IntelliJ IDEA](https://www.jetbrains.com/idea/download/)

**Atom:**
- **Ease of Use:** Known for simplicity and ease of customization. Clean interface and straightforward package management make it accessible.
- **Compatibility with Project Requirements:** Supports various languages and offers community-developed packages for extended functionality.
- **Collaboration Features:** Features Git integration for version control. Essential collaboration tools for small to medium-sized teams.
- **Overall Development Efficiency:** Offers a smooth coding experience with a focus on customization. Lightweight nature contributes to a responsive and efficient development environment.
- [Download Atom](https://atom.io/)

**Note:**
While these IDEs were considered, my team and I have chosen Visual Studio Code (VSC) due to our familiarity and comfort with it, believing it to be the best choice. You are not obligated to use VSC; feel free to choose from the recommended IDEs or any other preferred IDE. We do recommend VSC for its versatility and our positive experience with it.
