### ISSUE TITLE
Milestone #2 Presentation Attribution - Human Interfaces Team 👥

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#110]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Human Interfaces team towards the proper documentation and development on the **_Milestone 2 Presentation_**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, March 8 2024** 🚨

**Comment by Javi510348** [comment]
I worked with the first Achievements slide and highlighted 4 tasks that were done during this milestone.

Also, created the first slide for Human Interfaces in which it includes the name of every team member.

**Comment by Saul-Caban-UPRM** [comment]
I worked with the future goal slide creating and expanding ideas for the team to aim for the next milestone.

**Comment by frances-sepulveda** [comment]
I worked with future goals slide!

**Comment by jhsanchez26** [comment]
Worked with the achievement slide to better convey our progress during this milestone.

**Comment by yamayrie** [comment]
worked with the new user verification methods slide and added snippets of the code

**Comment by 1uismar33r0** [comment]
Worked with the new queries slide to present the queries and to exlplain their function
