### ISSUE TITLE
FOOTER - Home Page Optimization 

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#113]
### **Split Task from https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/issues/39#issue-2135081696.** 

Create a footer section for the website containing links to important pages such as 'About Us', 'Contact Us', 'Frequently Asked Questions', 'Terms of Service', and 'Privacy Policy'. 

**Optional**: Add social media icons to connect the user on different platforms.

**Comment by evnd04** [comment]
Approved
