### ISSUE TITLE
Create a profile logo.

### ISSUE THREAD

**Issue by HectorSepul** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#117]
Creates the profile logo to access the profile.

**Comment by evnd04** [comment]
What do you mean by profile logo? Like in some apps it's simply the profile photo that you click on to access the settings and profile info, would this be the case or is it a different logo?

**Comment by HectorSepul** [comment]
Yeah like you said, its the profile logo that people usually edit with a pic.

**Comment by HectorSepul** [comment]
added the profile circle symbol to the home page file.
