### ISSUE TITLE
Profile logo and pop-up window

### ISSUE THREAD

**Issue by HectorSepul** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#118]
Makes the profile logo work and after you click the profile, it opens a pop-up below the logo.

**Comment by HectorSepul** [comment]
After i do the logo, this task is to be able to interact with the logo, and access its settings.

**Comment by rukitoyordan** [comment]
@HectorSepul, what is the status on this? Also make sure to describe properly your tasks

**Comment by ErickCruz4** [comment]
Objective:
Implement an interactive settings menu accessed via a button that pops up a mini window with links to various user profile settings.

Task Description:
Create a button associated with the profile logo on the home page. Upon clicking this button, a mini window should pop up displaying at least four links to different user settings pages, x, x, modifying x, and x.

Implementation:

Design and integrate a button adjacent to the profile logo on the home page.
Develop a mini window component that appears upon clicking the button, containing at least four clickable links.
Link each menu item to its respective settings page within the application.
Subtasks:

Design and implement the button for accessing the settings menu.
Develop the mini window component to display the settings links.
Create the individual settings pages to which the links will navigate.
Testing and Debugging:

Click the button associated with the profile logo on the home page to verify that the mini window appears.
Test each link within the mini window to confirm they navigate to the correct settings pages.
Ensure the appearance and functionality of the settings menu align with the established design and user experience standards.
Deadline:
Complete the implementation and testing of the interactive settings menu with the specified functionalities by April 19, 2024 (edited)

we are almost finished with this task

**Comment by HectorSepul** [comment]
This task is completed.
