### ISSUE TITLE
Pet Profile Interaction

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#124]
# Pet Profile Interaction:

## Objective:
Enable users to interact with pet profiles by providing options to like, share, and contact the owner or shelter responsible for the pet's care.

## Task Description:
This task involves implementing features to facilitate user interaction with pet profiles. Users will be able to express interest or appreciation for a particular pet by clicking on a "Like" button. Moreover, a mechanism will be provided for users to initiate communication with the owner or shelter. This communication feature may involve a designated button or link that leads to a contact form where users can input their details and message, which will then be sent directly to the owner or shelter. Alternatively, contact information such as email addresses or phone numbers may be provided for users to reach out through their preferred method of communication.

## Implementation:
- Add "Like" button functionality to each pet profile.
- Develop a contact form for users to input their details and message.
- Provide contact information (email addresses, phone numbers) for direct communication, if applicable.

### Subtasks:
- Implement "Like" button functionality.
- Integrate sharing options for pet profiles.
- Design and implement a designated button or link for contacting the owner or shelter.
- Provide contact information (email addresses, phone numbers) if a direct communication method is preferred.

### Testing and Debugging:
- Conduct testing to ensure the "Like" button works correctly and accurately records user preferences.
- Test sharing options to ensure pet profiles are shared accurately across various platforms.
- Validate the functionality of the contact button or link, ensuring it redirects users to the appropriate contact form or contact information.
- Test the contact form to verify that user messages are correctly delivered to the intended recipient.
- Debug any issues encountered during testing to ensure smooth functionality.
### Deadline:
Apr 25, 2024

**Comment by evnd04** [comment]
I like this intractability, but if I'm not mistaken the website management team is working on a bookmark feature instead of a like feature you should implement a similar bookmark feature since likes could also be a little saddening to pets with no likes. I like the idea of a bookmark system or a no-show-like system that only you and the pet profile manager could see. Ill approve this right now though good work.

**Comment by rukitoyordan** [comment]
@RaquelQuinones, your task seems properly defined, but if you are able to use the task template given with an actual deadline for you, I would appreciate it! Thanks

**Comment by RaquelQuinones** [comment]
@rukitoyordan Do you want me to comment with task template or edit the issue?

**Comment by RaquelQuinones** [comment]
@rukitoyordan Done with the template.
