### ISSUE TITLE
Add Milestones and Events to Activity Log

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#125]
Include/ add key milestones and events of the adoption process in the Activity Log.

**Comment by rukitoyordan** [comment]
@RaquelQuinones, what is the status of this? Also, make sure to properly describe your tasks for them to have proper approval.

**Comment by RaquelQuinones** [comment]
Is not currently being worked on.
