### ISSUE TITLE
Retrieve and Store Data - Activity Log

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#126]
Develop a functionality to store and retrieve activity log data.

**Comment by rukitoyordan** [comment]
@Alejandro-DeJesus, you can't close issues without manager approval. Please let us know with more detail what you did in this task and why is it considered 'Done'

**Comment by rukitoyordan** [comment]
@RaquelQuinones @Alejandro-DeJesus what is the status of this?

**Comment by RaquelQuinones** [comment]
The activity log is not currently being worked on. The description of each task was provided in the first milestone issue on the activity log. If further description on the task is necessary, please let me know.
