### ISSUE TITLE
Initialize DataBase- Pet Profiles

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#13]
# Initialize DataBase #

## Description ##
> **The data base of the pet profiles is to store various pieces of information related to the pets, their profiles, and associated data. Some essential components of the databases are:**

1. Pet ID: The unique identifier for each pet profile.
2. Name: The name of the pet.
3. Species: Species of the pet (cat,dog,bird,rabbit,ect...)
4. Breed: The breed of the pet (if its applicable)
5. Age: Age of the pet.
6. Gender: Gender of the pet (male,female,other)
7. Size: Size of pet (small, medium,large)
8. Color: Coat pattern or color of the pet.
9. Description of the pet's personality, or any special characteristics.

**Comment by RaquelQuinones** [comment]
Other thing to add to the databases :
1. Images (could also add videos) to display the pets in their profiles
2. Health and Medical Information, like vaccines, health records or any other medical history.
3. The status of their adoption (Available,Pending, or the Date of when the pet got adopted)
4. Location and Shelter information. (Contact Information)
5. The loggings of the pet profile (Date the profile was created, last updated,etc..)

**Comment by RaquelQuinones** [comment]
Professor suggestion -> User's initialize the database

**Comment by evnd04** [comment]
Good initiative and all the info is necessary though I feel like the color section is not that necessary since pictures of the pets will be available, it could still be present but not entirely necessary. Also, a heads up, for the Databases we will probably use PostgreSQL. Autoincrementing IDs are also a good idea for the ID section.

**Comment by RaquelQuinones** [comment]
The initialization of the database task has been completed. Me and Alejandro had a meeting where we laid the solid foundation for storing and managing the pet profiles and the associated data for it. We decided to break down the initialization process into multiple task, that were divided into the first milestone and the second milestone, to make it easier to manage and track the process of the Pet Profiles. Each task will be either handled individually or in teams of two, leading to have a successful database setup. Another part is we will continue to have the weekly meeting to work on the code and also communicate and update each team member on the work accomplish.
