### ISSUE TITLE
Notification Bar - Activity Log

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#130]
Primary use is to allow users to view upcoming appointments and receive notifications about new appointment  or updated appointments. It should feature necessary information.

**Comment by rukitoyordan** [comment]
@RaquelQuinones, please provide a more detailed description and let us know if this is being actively worked on or not.

**Comment by RaquelQuinones** [comment]
This is not actively worked on.
