### ISSUE TITLE
Create feature to store Legal Documents - PetProfiles

### ISSUE THREAD

**Issue by RaquelQuinones** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#131]
# Store Legal Documents:
## Objective:
The objective of this task is to develop a feature that captures and stores the necessary information to demonstrate compliance with legal requirements and regulations related to pet adoption.

## Task Description:
This task involves creating a feature that captures and securely stores information essential for demonstrating compliance with legal requirements and regulations pertaining to pet adoption. The feature will ensure that all necessary data, such as adoption records, documentation, and other pertinent information, are collected and stored appropriately. 

## Implementation:
- Collect relevant information required for legal compliance in pet adoption.
- Integrate encryption and other security protocols to safeguard sensitive information.
- Showcase in the pet profile the documents and essential information of the pet. 

### Subtasks:
1. Define the required data fields and forms to capture necessary information for legal compliance.
2. Create user interfaces: Design and develop user interfaces for data entry and retrieval, ensuring usability and accessibility.

### Testing and Debugging:
- Conduct comprehensive testing to ensure the accuracy and reliability of data capture and storage functionalities.
- Test access control measures to verify that only authorized users can access the information.
- Debug any issues encountered during testing to ensure the functionality of the feature.

### Deadline:
Apr 25,2024

**Comment by evnd04** [comment]
Very necessary, vaccines and similar health requirements should also be displayed if not planned already. Approved

**Comment by rukitoyordan** [comment]
@RaquelQuinones, please make sure to properly define the task. You have 24 hours, otherwise it will be denied for further development.

**Comment by RaquelQuinones** [comment]
@rukitoyordan Alright, it will be done for tomorrow. Should I add the task template in the comment or edit the issue?

**Comment by RaquelQuinones** [comment]
@rukitoyordan  Done with the template.
