### ISSUE TITLE
 Implement Call-to-Action Buttons - Home Page Optimization

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#133]
**Description:**
We aim to enhance user engagement and interaction on the homepage by strategically placing call-to-action buttons. These buttons will serve as essential entry points for users, encouraging them to take specific actions related to adoption, donation, volunteering, and learning more about the adoption process.

Please feel free to leave any suggestions or new ideas for call-to-action buttons down below in the comments.

**Subtasks:**

1. **"Donate Now" Button:**
   - Design and integrate a compelling "Donate Now" button.
   - Position the button prominently to attract attention and encourage users to contribute.
   - Link the button to the donation section.

2. **"Become a Foster" Button:**
   - Develop a visually appealing button.
   - Strategically place the button to capture user attention and prompt engagement.
   - Link the button to information about the process of becoming a foster for RUMAR.

3. **"Learn More" Button (About Adoption Process):**
   - Create and implement an inviting "Learn More" button specifically for understanding the adoption process.
   - Ensure the button is strategically positioned for easy access.
   - Link the button to a dedicated section providing comprehensive information on the adoption process.
   
**Note:** This task is part of a broader initiative mentioned in Task https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/issues/39.

**Deadline:**
Monday, March 18, 2024

**Comment by evnd04** [comment]
Will the donate now button take you to a donation page? And if so, what would be displayed there since as discussed, they do have an "ATH movil" number maybe it displays that number.?

**Comment by smbv** [comment]
@evnd04 Not completely sure if the donation button will be implemented yet. If it is implemented it would display the ATH movil information

**Comment by rukitoyordan** [comment]
@smbv, is this actively being worked on or still in the Backlog? Let me know because we are near the end of the milestone!

**Comment by smbv** [comment]
@rukitoyordan this task is done.
