### ISSUE TITLE
Create Basic Pet Registration page

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#135]
The goal is create a page that asks for the information of a new potential pet, to be added to the database. This version is about establishing basic functionality with minimal concern for aesthetics. Allowing the user to input the pets information. 

The information to be asked:
-Name
-Age
-Species
-Sex
-Images
-Personality

Deadline Monday, March 11, 2024

**Comment by evnd04** [comment]
What information will be asked for? Approved but add it to the description of the issue.

**Comment by Alej24** [comment]
For the time being, i added a button called Pet Registration to the home page which leads to the pet registration page when clicked.  I will try to make it a bit more aesthetically pleasing, and if any changes need to be made, please let me know. 

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99218281/ad42b267-cf9c-4f37-abc8-801143fa1dc3)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99218281/06755352-40bc-4464-a13d-da3535d86826)

**Comment by Christian2101** [comment]
Made the aesthetic changes to the Registration Form.
