### ISSUE TITLE
Creation of Routes for Pet Profile page

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#139]
The objective is to add one route from the home page to the pet profile page, and another route from the pet listings page to the pet profile page. This so that users can access the pet profile page upon clicking on a pet they are interested in. 

additionally there must be a route back so that a user can return to the home page/pet listing page as they desire.

Task is complete once all routes are created, and functional.

**Comment by evnd04** [comment]
Approved

**Comment by RaquelQuinones** [comment]
The routes from the Home Page to the Pet Profiles are complete. You can click on either Apollo's or Luna's photo on the home page to view the profile of that pet.
