### ISSUE TITLE
Creation of Routes for Pet Listings page

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#140]
The objective is to add one route from the home page to the pet listings page, and another route from the pet profile page to the pet listings page. This so that users can access the pet listings page to browse the selection of pets available for adoption.

additionally there must be a route back so that a user can return to the home page/pet profile page as they desire.

Task is complete once all routes are created, and functional.

**Comment by diegorobles2** [comment]
Route from home page to the Pet Listings page is done.
