### ISSUE TITLE
[Email Verification] Sending Email with Code

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#141]
With this task we are going to research and implement the best method to generate a code that it will be sent via email to the user after signing up, to be able to confirm the authenticity of the email provided for the account. The user will not be able to do anything without confirming the email address.
 

Due Date: 3/15/2024

**Comment by evnd04** [comment]
Approved

**Comment by Saul-Caban-UPRM** [comment]
Worked on the files sendEmail.js, users.js (under the folder of controller,) and signup.ejs. On the file named sendEmails, I created an email to send confirmation tokens to the user to be able to confirm the email. If you wish to log into the account please contact me by commenting here. The email is also in the code, but the password is different from the one used in the files. On signup.ejs file simply changed the message pop up. Finally on the Users.js file implemented the logic to be able to send the email.

Also, me and @Javi510348 tested the code and made sure everything went smoothly.
