### ISSUE TITLE
[Lecture Topic Task] Pet Interfaces Class Diagram 🪿

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#149]
The purpose of this task is to **generate a class diagram for describing Pets**. This will be worked as a _**Lecture Topic Task**_ in conjunction with all Pet Interfaces. Every member is responsible for contribution to this and to have it fully implemented **before Milestone 2** ends to be added to the Milestone 2 Documentation.

Reminder: The purpose of class diagrams is to project aspects of the project and help with other presentations. These help clarify any types of behaviors portrayed in said topic.

> - They show structural relationships among entities or classes
> - Show key actions, operations or methods associated
> - You can have a domain driven design based on source code

Some important components that the diagram(s) must have are as follows:
## Classes/Entities

> - Name
> - Attributes
> - Operations

## Relationships 

> - Association
> - Dependencies
> - Composition
> - Aggregation
> - Inheritance
> - Implementations

**Comment by Alejandro-DeJesus** [comment]
The pet's class diagram was completed and added to the documentation. detailing all of its attributes and operations and which operations it shared with the user class.
