### ISSUE TITLE
Featured Animals - Home Page Optimization

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#155]
Highlights adoptable animals with high-quality photos & compelling descriptions.
Include a mix of:

- Animals waiting the longest

- Animals with special needs
- "Staff picks"
- New arrivals

Note: This task is part of a broader initiative mentioned in Task https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/issues/39.

**Comment by evnd04** [comment]
Approved

**Comment by Adriana-Isabel** [comment]
I'm thinking of moving and doing this task to Milestone 3, is that ok?
@evnd04 @rukitoyordan

**Comment by Adriana-Isabel** [comment]
Task finished!
