### ISSUE TITLE
Documentation 1.2.1 - Current Situation

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#156]
Documenting 1.2.1. Current Situation: In your current situation you write "We aim to fix this..." that's already talking about your ideas on how the remedy the situation.

**Comment by evnd04** [comment]
Approved

**Comment by Adriana-Isabel** [comment]
Currently, the RUMAR Association on campus faces challenges in pet adoption due to the complexity of the adoption process and a lack of promotion for this service. As a result, pets cared for by fosters may remain in their care for extended periods without attracting potential adopters. To address these issues, we propose implementing a simplified pet adoption system. This system will provide users with easy access to essential information about available pets, including their names, ages, sizes, behaviors, and any relevant certificates (such as for service animals). By offering a user-friendly interface that showcases a wide variety of animals and their associated details, we aim to facilitate the adoption process and help users find the perfect pet for their needs.
