### ISSUE TITLE
Documentation 1.2.2 - Needs

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#157]
**_Documenting 1.2.2. Needs:_** In the section "Need" you talk about "require a system". We talked about this in class: people normally do not need the system, what they need can be provided by your system, but if it were provided in any other way, people would normally be just as happy. In all these bullet points, where you talk about the app, features of the system-to-be, and similar, you are talking about your ideas on how to satisfy needs and not about the needs themselves.

**Comment by evnd04** [comment]
Approved

**Comment by Adriana-Isabel** [comment]
1.2.2 Need
    ·       Streamlined Adoption Process: Users seek a simpler and more accessible process for adopting animals. They desire a process that is easy to navigate and understand, reducing barriers and complexities associated with adoption.

    ·       Animal Welfare Promotion: There is a need to raise awareness about animals available for adoption and the adoption process itself. Users require access to information that highlights the importance of pet adoption, encourages responsible pet ownership, and promotes the welfare of animals in need.

    ·       Community Engagement: Users seek opportunities to connect with like-minded individuals and organizations within the community. They desire a sense of belonging and support in their journey towards adopting and caring for pets, fostering a collaborative environment that benefits both animals and adopters.

    ·       Efficient Communication: Users require timely and reliable communication channels to stay informed about available animals, adoption events, and important updates from relevant organizations. They value transparency and accessibility in communication, ensuring that they can make informed decisions about pet adoption.

    ·       Educational Resources: Users seek access to educational materials that empower them to become responsible pet owners. They require information on topics such as pet care, behavior training, and the benefits of adopting from shelters or rescue organizations, enhancing their ability to provide a loving and nurturing home for their pets.

    ·       Data Management: There is a need for effective data management practices to ensure accountability and transparency in the adoption process. Users expect organizations to maintain accurate records of animal adoptions, medical histories, and program impact, fostering trust and confidence in their operations.

    ·       Flexibility in Adoption Criteria: Users value flexibility in adoption criteria to ensure that animals are placed in suitable and loving homes. They appreciate organizations that consider their individual circumstances and preferences when facilitating the adoption process, prioritizing the well-being of the animals above all else.

Focusing on these underlying needs, we can develop solutions that effectively address the challenges and concerns of our users, ultimately enhancing their experience with pet adoption.
