### ISSUE TITLE
Same font styles as home page / Pet Listings Page Design

### ISSUE THREAD

**Issue by diegorobles2** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#160]
To maintain consistency across the website, apply the same font styles used on the Home page to the Pet Listings page.

**Comment by evnd04** [comment]
Provide more information on what exactly was done and achieved in this task

**Comment by diegorobles2** [comment]
The new font is applied to the entire body to maintain consistency with the home page.
The font styles for the header from the home page are replicated for the header on the pet listing page.
The font styles for the pet listings remain the same as before, maintaining consistency with the rest of the page.
