### ISSUE TITLE
Tabs for Pet Breed - Pet Listings

### ISSUE THREAD

**Issue by JohnSantiagoRuiz** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#17]
A good place to start would be to create tabs where it can be identified what type of pet it is. If we have tabs for each type of pet, it would be easier to find the exact pet the person would want and more organized. 

An example would be on tab for dogs, one tab for cats, etc.

**Comment by evnd04** [comment]
Great idea, the pet profiles team is thinking of adding pet species into the database so it would probably be relatively simple to implement a filter or tabs for each type of species. Though most animals in RUMAR are probably cats and dogs, maybe implement a filter for breeds as another task? Since breed info is also a part of the database.

**Comment by JohnSantiagoRuiz** [comment]
Yes, that was part of my idea but I was planning to implement it after the species tabs.

**Comment by rukitoyordan** [comment]
@JohnSantiagoRuiz as a checkup, just wanted to know the status of this as a whole. Thank you!

**Comment by JohnSantiagoRuiz** [comment]
This task is being worked on at the moment.

**Comment by rukitoyordan** [comment]
@Alej24, please make sure to properly describe this task in a more detailed manner. To quote the professor:

> it's the responsibility of the managers not to assign tasks that are not yet sufficiently well defined AND it's the developers' responsibility not to take any tasks that are not yet well enough defined. For milestone 3, I will not accept tasks that, at the end of the milestone, are as insufficiently defined as this. The developer will not get the score and the manager's score will also be affected.

**Comment by diegorobles2** [comment]
Implement a tab for dogs, cats and all pets for the user to select when searching for a pet. Each selected tab should filter out pets that doesn't meet the requirements. The design for the tabs needs to be simple and follow the same color theme as the page (green). This tab feature combined with the size filter will make the pet search faster and easier for the user.
