### ISSUE TITLE
[OLD Missing Issue] Main Branch Fix

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#174]
On March 13,2024 there was an issue after a merge from a branch to main. Almost all of the code, that was available at the moment was deleted. @Saul-Caban-UPRM and I worked together to fix the issue by rebasing  the new branch with an old copy of the main branch that had all of the latest updates before the merge. After rebasing the code, we tested every feature that was working to make sure that everything was up to date once again.

**The issue was not added the same day as the problem due to the necessity of fixing the problem so we could prevent further issues.

If you have any questions please let us know.

**Comment by evnd04** [comment]
Approved
