### ISSUE TITLE
 Visual Studio Code and Local Server Configuration

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#18]
In this task, the focus is on setting up Visual Studio Code (VSC) for the RUMAR Adoption Project's website development. This task lays the foundation for a well-equipped development environment, ensuring that the team can seamlessly collaborate and code. Follow these steps for an efficient and streamlined coding environment:

1. Download and Install Visual Studio Code:
   - Visit the official Visual Studio Code website linked here to download the latest version.
   - Follow installation instructions based on your operating system.

2. Install Necessary Extensions:
   - Enhance VSC's capabilities by installing extensions for the preferred programming language.
   - Explore and add extensions that align with the project's specific requirements for web development.

3. Configure VSC Settings:
   - Optimize the development environment by adjusting Visual Studio Code settings.
   - Customize preferences, themes, and other configurations to suit the team's preferences and coding style.

4. Set Up a Local Development Server with Live Reloading:
   - Facilitate a smoother coding experience by configuring a local development server.
   - Enable live reloading to instantly preview changes during the development process.
   - Provide documentation or links to resources that assist team members in implementing these features effectively.

**Example Code/Resources:**
- Download VSC here: [Visual Studio Code](https://code.visualstudio.com/download)
- Local Server Option: [Live Server Extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer&ssr=false#qna)

**Recommended Extensions**
**Recommended Extensions**

1. **[Official Node.js extension:](https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack)**
   - A comprehensive extension pack for Node.js development, including debugging, linting, and IntelliSense support.

2. **[JavaScript (ES6) code snippets (alternative):](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaScriptSnippets)**
   - Boost productivity with JavaScript ES6 snippets.

3. **[EJS Language Support:](https://marketplace.visualstudio.com/items?itemName=DigitalBrainstem.javascript-ejs-support)**
   - Enhances Visual Studio Code's support for EJS (Embedded JavaScript) with syntax highlighting and IntelliSense.

4. **[MySQL (alternative):](https://marketplace.visualstudio.com/items?itemName=formulahendry.vscode-mysql)**
   - Language support for MySQL within Visual Studio Code, aiding database-related coding tasks.

5. **[Tailwind CSS IntelliSense:](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss)**
   - IntelliSense and autocompletion support for Tailwind CSS, streamlining the styling process.

6. **[JavaScript Debugger (alternative):](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug)**
   - Debug your JavaScript code in the Chrome browser directly from Visual Studio Code.

7. **[GitLens:](https://marketplace.visualstudio.com/items?itemName=eamodio.gitlens)**
   - Supercharge the Git capabilities in Visual Studio Code with features like an interactive history, blame annotations, and code lens.

8. **[Prettier - Code formatter:](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode)**
   - Ensure consistent code formatting with Prettier, supporting various languages including JavaScript and HTML.

9. **[npm Intellisense:](https://marketplace.visualstudio.com/items?itemName=christian-kohler.npm-intellisense)**
    - Autocomplete npm modules in import statements, speeding up the process of adding dependencies.

10. **[Code Spell Checker:](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)**
    - Detect and correct spelling mistakes in your code and comments.

11. **[REST Client (alternative):](https://marketplace.visualstudio.com/items?itemName=humao.rest-client)**
    - Test your REST APIs directly within Visual Studio Code with this powerful REST client.

12. **[Path Intellisense:](https://marketplace.visualstudio.com/items?itemName=christian-kohler.path-intellisense)**
    - Autocomplete filenames, making it easier to navigate and import files in your project.

13. **[Prisma (alternative):](https://marketplace.visualstudio.com/items?itemName=Prisma.prisma)**
    - Tools for interacting with databases, including MySQL.

Before installing any extensions, review their descriptions and user reviews to ensure they align with your project's requirements. Extensions can be installed directly from Visual Studio Code's Extensions view or via the provided links.

**Note:**
You're not required to download all the suggested extensions; pick the ones that align with your project needs. The "Live Server" extension is recommended for enhanced functionality. Feel free to explore and share additional extensions that work well for your workflow in the comments below. Happy coding!

Deadline: 
- Aim to complete by 02/12/24

**Comment by rukitoyordan** [comment]
Once you figure out the extensions needed let us know so that we can encourage the rest of the teams to download them for ease of access for when you provide the base code of the website

**Comment by rukitoyordan** [comment]
Extension Links need Fixing:

- [Express Snippets:](https://marketplace.visualstudio.com/items?itemName=xabikos.JavaJavaScriptSnippets)

- [MySQL Language Support:](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-mysql)

- [Bracket Pair Colorizer:](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer)

Doesn't work for me, just takes me to a 404 Error page.

Some doubts:

- [Node.js Extension Pack:](https://marketplace.visualstudio.com/items?itemName=waderyan.nodejs-extension-pack)

This shows as a deprecated extension inside of VSCode. This is not an issue, but making sure you are certain this is the best extension for the usage you wish to embark for.

- [Debugger for Chrome:](https://marketplace.visualstudio.com/items?itemName=msjsdiag.debugger-for-chrome)

This is fully deprecated and when I go to VSCode Marketplace on the actual app (not website) it recommends we use:

- [JavaScript Debugger](https://marketplace.visualstudio.com/items?itemName=ms-vscode.js-debug)

Let me know if you think this would be more viable. 


Please make sure to get back to me on this and fix any of the URLs that might be having trouble. Lastly, kudos for also adding organizational extensions! 💛

**Comment by smbv** [comment]
@rukitoyordan, I fixed the issues with the deprecated and non-working extension links in the recommended list. I deleted the non-working links and substituted them with working links from similar extensions. The alternatives now have "(alternative)" specified.

Everyone, please remember that these suggestions are not mandatory. Team members and managers as well are encouraged to explore and recommend other extensions they find beneficial. If any link becomes inactive or if you discover new extensions that might enhance our development environment, please share them in the comments and provide an alternate working link. The goal here is to create a collaborative and efficient coding experience.

**Comment by GiovanniMaysonet** [comment]
I have finished working on this task.
