### ISSUE TITLE
Review documentation

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#182]
Ensure documentation added by Human Interfaces 2.1.2, 2.1.3, 2.2.3 complies with the requirements given by the professor.

**Comment by rukitoyordan** [comment]
In the Milestone 2 Attribution, we are already taking into consideration everyone's revision and writing process in an equal way so that everyone has the same opportunities for points in the Milestone. Please refer your contributions to #104
