### ISSUE TITLE
Addition and Changes to the Persona Section of the Documentation (2.2.2)

### ISSUE THREAD

**Issue by GiovanniMaysonet** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#187]
Changed and replaced the Persona section with the applications of the concept we've implemented thus far in the website management theme.

**Comment by rukitoyordan** [comment]
@GiovanniMaysonet, we already created since the beginning of the Milestone, a centralized tasks for everyone in your team to put their contributions, please refer to #102
