### ISSUE TITLE
Pet species filter

### ISSUE THREAD

**Issue by AlexisTraversoPR** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#189]
Filter by species in the pet listings page for those who are only interested in looking at dogs or viceversa

**Comment by rukitoyordan** [comment]
@AlexisTraversoPR are you planning on doing this before the Milestone ends or after? Make sure to give me more description too!

**Comment by AlexisTraversoPR** [comment]
I already did it. I am waiting for approval to close it for this milestone.
