### ISSUE TITLE
Website creation and Git and GitHub Integration

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#19]
This task focuses on establishing Git and GitHub integration to ensure effective version control for the RUMAR Adoption Project. The team will establish a robust version control system, enabling efficient collaboration and ensuring a well-organized project structure. Follow these steps to streamline collaboration and manage project history:

1. **Download and Install Git:**
   - Navigate to the official Git website and download the latest version.
   - Follow the installation instructions based on your operating system.
   - Ensure that Git is properly configured on your machine.

2. **Integrate Visual Studio Code (VSC) with GitHub:**
   - Enhance collaboration by integrating Visual Studio Code with GitHub.
   - Configure VSC settings to seamlessly connect with your GitHub repository.
   - Provide documentation or resources on best practices for linking VSC and GitHub for version control.

3. **Create a File Structure for the Project:**
   - Establish an organized file structure for the RUMAR Adoption Project.
   - Define folders for different components (e.g., HTML, CSS, JavaScript) to maintain a clear and structured project layout.
   - Consider using a README file to document the project structure and provide essential information for team members.

**Example Code/Resources:**
- Install Git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
- Pair VSC with GitHub: https://youtu.be/mR9jhYD3bnI?si=N-SOT9bu0g65vBFB
- How to make a website: https://youtu.be/gQojMIhELvM?si=H4uwjFjpZavigqaA
- File Structuring: https://youtu.be/gFKsEab2-iA?si=BQS2J_1rtjvEHCT3

**Timeline and Deadline:**
- Aim to complete by: 2/12/24

**Comment by rukitoyordan** [comment]
Make sure to let us know what you will be using. @evnd04 had mentioned we can possibly use React rather than JavaScript for the project layout

**Comment by smbv** [comment]
@rukitoyordan I think @christianperez42 is in the process of uploading the programming languages that will be used for the project in his task.

**Comment by rukitoyordan** [comment]
> @rukitoyordan and @evnd04, @christianperez42 has already shared which programming languages will be used for the project in his task #10

I just saw it! Looks good. I think the technology stack seems robust and manageable.

**Comment by rukitoyordan** [comment]
Note here @smbv @Adriana-Isabel @christianperez42,

Install Git: https://git-scm.com/book/en/v2/Getting-Started-Installing-Git
Pair VSC with GitHub: https://youtu.be/mR9jhYD3bnI?si=N-SOT9bu0g65vBFB

Very good reasources. Once you actually do the repo make sure to publish it here so that the other teams can start working on implementing their features into the website. Great job! 👏

**Comment by smbv** [comment]
To get started with our RUMAR Adoption Website project, please clone the repository using the following command:

git clone https://github.com/uprm-inso4101-2023-2024-s2/RUMAR-Adoption-Website.git
