### ISSUE TITLE
Review Remember-Me feature

### ISSUE THREAD

**Issue by jhsanchez26** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#195]
Will review remember-me feature to confirm the functionality of the remember me check box and the saving of both username and password.

**Comment by jhsanchez26** [comment]
Successfully reviewed remember-me function and implementation for the log in page.

**Comment by rukitoyordan** [comment]
@jhsanchez26, please make sure to add the "pending manager" label and to not close any issues without approval. Next time we will not approve of this.
