### ISSUE TITLE
New Feature: Implement CAPTCHA

### ISSUE THREAD

**Issue by frances-sepulveda** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#196]
Integrating CAPTCHA into the login process is a powerful method to deter automated login attempts and enhance security by distinguishing human users from bots. Through tasks that are simple for humans but challenging for automated scripts, such as recognizing distorted text or identifying objects in images, CAPTCHA protects user accounts against brute force attacks. This straightforward addition to the login page effectively increases security without significantly impacting user experience, ensuring a balance between accessibility and protection against unauthorized access.

**Comment by evnd04** [comment]
Approved but, when possible, add implementation ideas, and possible ways to implement the captcha system into the existing website framework.

**Comment by HectorSepul** [comment]
As soon you press log in it will ask you to complete a captcha task.

**Comment by HectorSepul** [comment]
The captcha is completed, but I will need to create a generator for random captcha codes.
