### ISSUE TITLE
Create a page that displays all users

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#199]
Once a faculty column was added to the user table in the database the team encountered that now they needed a way to modify this variable. It doesn't make sense to allow any user to have the power to assign themselves as faculty members or not. So all users will be assigned a FALSE value in the faculty column and this page will make changes to the database based on the inputs of another faculty member.

Create an admin page that will :
- Display all users in boxes, similar to the implementation of the faculty tab in the website.
- Allow future modifications to the users that the members of the faculty might need to do. For the moment it will allow the faculty user to see and specify those who are members of the faculty.

**Comment by evnd04** [comment]
Add more to the description of the overall task, implementation included and background on why its needed.

**Comment by evnd04** [comment]
Approved: So this is basically a way so that only members of staff can change the status of a user based on if theyre faculty or not?
