### ISSUE TITLE
Admin page accessible for only admins

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#201]
Ensure the admin page is only accessible to those users who are members of the faculty. This will prevent nonfaculty users from getting access to all the user information and/or modifying it. 

This can be implemented first checking whether the faculty column of the current user contains a value of TRUE. From there on we can make the page tab visible to only those who faculty column holds a TRUE value.

**Comment by rukitoyordan** [comment]
@Angel-Rosado, is this task being actively worked on?
