### ISSUE TITLE
Captcha random image generator.

### ISSUE THREAD

**Issue by HectorSepul** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#202]
Generates a random picture with a different code that the user has to enter every time that they log-in. User Should be able to refresh the page and it should update the captcha-image with another code. The user needs to enter the code to access its account.

**Comment by evnd04** [comment]
Add more to the task description.

**Comment by evnd04** [comment]
Approved but add some info on the implementation when possible to provide a full overview of the task.

**Comment by ErickCruz4** [comment]
Objective:
Implement a CAPTCHA-based security feature for user authentication that generates a random image with a verification code upon login.

Task Description:
Introduce a CAPTCHA challenge during the login process to enhance account security. This feature should display a random image containing an alphanumeric code that the user must enter correctly to access their account. Additionally, provide a refresh option allowing users to generate a new CAPTCHA code if needed.

Implementation:

Design a CAPTCHA component to generate a random image with an alphanumeric code upon login.
Integrate the CAPTCHA component into the login page, adjacent to the username and password fields.
Implement a refresh functionality that allows users to generate a new CAPTCHA code by clicking a refresh button.
Subtasks:

Develop the CAPTCHA generating corresponding images.
Design and integrate the CAPTCHA component into the login page layout.
Implement client-side validation to ensure correct code entry before allowing account access.
Create a refresh button functionality to regenerate a new CAPTCHA code and image without reloading the page.
Testing and Debugging:

Verify that the CAPTCHA image and code display correctly upon loading the login page.
Test the refresh button functionality to confirm it updates the CAPTCHA image and code without requiring a page reload.
Validate the CAPTCHA code entry process by ensuring only correct codes allow successful login attempts.
Address any design inconsistencies or functional issues identified during testing to optimize user experience and security.
Deadline:
Complete the implementation and testing of the CAPTCHA-based security feature by April 19, 2024. 

we are working this

**Comment by rukitoyordan** [comment]
@ErickCruz4 @HectorSepul, what is the status of this task?

**Comment by ErickCruz4** [comment]
We are working on it. There is progress being made but we are not done yet.
