### ISSUE TITLE
Adding a Faculty requirement to Pet registration

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#205]
**Objective:**
Restrict pet registration to faculty members only, enhancing the system's control and ensuring that only authorized personnel can add pets to the database.

**Task Description:**
This task involves modifying the pet registration access control mechanism on a website. The objective is to check the logged-in user's faculty status. If the status is true, the user will be allowed to proceed to the pet registration form. If the status is false, the user no see the pet registration tab on their home screen.

**Implementation:**
User Authentication: Ensure that the user's login status and faculty attribute are validated at the beginning of the session.
Access Control Logic: Modify the existing pet registration workflow to include a condition that checks the faculty attribute of the logged-in user.
User Interface Adjustments: Update the user interface to obscure the pet registration tab if the uses is not logged in as faculty.  

**Subtasks:**
Modify Authentication System: Enhance the authentication system to reliably check and store the faculty status of users.
Update Pet Registration Workflow: Implement the logic to check the faculty status before allowing access to the pet registration form.
Database Adjustments: Ensure that the database supports the logging and retrieval of faculty status for each user.

**Testing and Debugging:**
attempt registering a pet as, a faculty member, a non faculty user and a non-logged in user. with the latter two being successful tests upon failure to register a pet.

Deadline
April 24, 11:59pm

**Comment by rukitoyordan** [comment]
@Alejandro-DeJesus, please properly define the task and let me know if this is actively being worked on. You have 24 hours to act on this.

**Comment by Alejandro-DeJesus** [comment]
this task is completed, is properly defining the task with the task template still necessary.

**Comment by evnd04** [comment]
If possible to change please do so to ensure no problems with the professors grading.
