### ISSUE TITLE
Adding Post Registration page

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#206]
Currently if a pet is registered it will send the user to a black screen. Users would instead be to sent to a page indicated if their registration was successful or not. This would be determined by seeing if the registered pet appears on the pets table in the database.
The Page should have text indicating the result of the test "Error: failed to register pet" or "Pet was successfully registered" for example.

additionally the web page should have a button allowing the users to either return to the home page or return to the pet registration form to register another pet if needed.

**Comment by Alej24** [comment]
I added a postPetRegistration page with a sample text that reads "Pet was successfully registered" and has the buttons that lead to home or to register another pet.  When the submit button is pressed on the petRegistration form, it leads to postPetRegistration regardless of if any information was filled on the form.  Its still missing the change in message depending on if the pet was successfully registered or not.

**Comment by Alej24** [comment]
postPetRegistration now works as it was intended.

**Comment by rukitoyordan** [comment]
@Alej24 so is this issue done?

**Comment by Alej24** [comment]
yes, it's finished.
