### ISSUE TITLE
Add Form_Details Table in the Database

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#208]
Once the user completes Form, we need to save of all of the form details in the database. This table will work together with the Form table, so we can link the primary key from the Form table to the Form_Details table. This will be done by using foreign keys in the database. 

Once the allowed personnel check all of the details of the form, he will decide if the form will be approved or not. 

The details regarding what type of information is going to be stored in this table will be seen in the form creation issue. The issue will be #209 . All of the answers to the questions, will be saved in this table.

Deadline: 10/04/2024

**Comment by evnd04** [comment]
Provide an overview of the form in this issue also not just the issue of form creation, or at least link to the form creation issue.

**Comment by Javi510348** [comment]
The details regarding what type of information is going to be stored in this table will be seen in the form creation issue. #209

**Comment by Javi510348** [comment]
The table has been added to the database with the name "form_details". Different columns were added in order to store the form information.  The columns were:

- details_id - Primary Key

- f_id (foreign key) - Here we will store the primary key from the "forms" table.  This is done so we know to which form the details are related to.

- address - It will store the home address provided by the user.

- housing_type - It will the housing type of the user. The options will be House or Apartment.

- people_house - It will store the number of people that lives in the house.

- num_pets - It will store the number of pets that the user has. If he has no pets, the default value will be 0.

- type_pets - If the user has any pets, he will write the type of animals that he has. It will store the info as text.

- adoption_reason - It will store the reason o adoption provided by the user.

- pet_location - It will store the location selected by the user. The options are indoor, backyard or both.


If anyone has any suggestion or question, please let me know.
