### ISSUE TITLE
Create profile page continuation. Profile editing feature.

### ISSUE THREAD

**Issue by RoBdIeL** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#211]
To enhance with new functionalities for managing user settings, including the secure updating of user credentials and personal details with robust argon2 hashing. A new route, /updateProfile, has been added, utilizing Express middleware to ensure that only authenticated users can update their profiles. However, it is crucial not to deploy these new features to the development environment without extensive testing, including unit and integration tests, to prevent potential issues and ensure the security and integrity of user data. Additionally, an AJAX-based dynamic feedback mechanism in the EJS templates improves user interaction by providing immediate confirmation of updates or displaying errors, thereby enhancing the overall user experience.

**Comment by evnd04** [comment]
Approved when possible, add what information would be accessible specifically and what could be changed, since I suggest not everything should be able to be edited.

**Comment by evnd04** [comment]
Add requested info before being graded

**Comment by rukitoyordan** [comment]
@RoBdIeL, please add a proper task description and let me know the status of this task. You have 24 hours to do so.

**Comment by RoBdIeL** [comment]
Sorry for the late answer. Here's what I've been working on:


The enhanced updateSettings function and the new updateUserProfile functionality extend the user management capabilities of the application, allowing for secure updates to user credentials and personal details such as bio and location using robust argon2 hashing. Integrated into the index.js file, a new route /updateProfile employs Express middleware for authentication, ensuring that only authenticated users can make profile updates. Despite the progress in developing these features, it is essential not to push this code directly to the development environment without thorough testing, including unit and integration tests, to prevent potential disruptions and ensure no new bugs compromise user data integrity. Comprehensive testing is critical to verify the effectiveness of the error handling mechanisms and the overall reliability of the new user settings management features.
The AJAX-based dynamic feedback mechanism in the EJS template provides real-time interaction, displaying success or error messages without reloading the page, thus enhancing the user experience by confirming settings updates immediately or highlighting errors in the input fields.

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/b33eeba1-b1c1-48ba-9b98-6d10110cb605)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/624e2dc5-d444-4b27-872b-fea5cc1847b9)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/9e2eb2f0-7b27-47a3-b14c-07dbdb2d9d29)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99343992/3c2fa7eb-c44f-4927-8e10-dc63ba791e51)
