### ISSUE TITLE
Add Form Information to Form and Form Details Tables ( Queries)

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#213]
**Objective**

Create two queries in which they will be responsible of adding the information from the form to the tables in the database.

**Description**

We need to create two queries in this task. One query will be responsible of adding information to the "form" table. By adding this information it will link the user with a pet and with a form. Meanwhile, the other query will be adding all of the information that will be asked to the user to the "form_details" table. Also,  two new files will be created with the name "Adoptionform.js" in the dao and controller folder.

**Implementation**

To be able to implement the full functionality of both queries, we need to add two functions in the dao  Adoptionform.js file and two functions in the controller Adoptionform.js file. The functions in the dao will be resposnsible of running the queries and the functions from controller will be responsible of managing the results from the queries. Finally, connect the submit button from the form to the queries.

**Deadline**

April 15, 2024

**Comment by evnd04** [comment]
Approved

**Comment by Javi510348** [comment]
@1uismar33r0  and I worked on the adoption queries responsible of adding the information to the database tables. At the moment, everything works correctly, but selecting a specific user and pet is hard-coded because we still don't have a session for the users. The next step will be creating user sessions once the users login.
