### ISSUE TITLE
Forgot Password Function

### ISSUE THREAD

**Issue by jhsanchez26** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#214]
**Objective:**
 Add a forgot password function
**Task Description:**
This feature should allow the user to see a button when logging in that allows them to change their password in case they forgot it. The user will receive an email with a temporary password so they can access their account and change their password.
**Implementation:**
Create a link that allows the user to click on it, upon clicking on it the user will receive a temporary password and change their old password. **Implementation may change, In case of any changes, it will be included by editing this post.** 
**Testing and Debugging:**
Test that the old password can't be used and make sure that the database has the updated password. Make sure that the user can log in with the new password by testing the login. 
**Deadline:**
April 20, 2024

**Comment by evnd04** [comment]
Use task template provided earlier this week to formulate tasks, its in a discussion tab in github.

**Comment by evnd04** [comment]
Approved

**Comment by jhsanchez26** [comment]
added forgotPassword button on login page which redirects user to a forgotPassword page. From there, they enter their email address and receive an email with a temporary password. They then input their temporary password, and if it matches, they get to change their password. The database is then updated with their new password.

**Comment by Javi510348** [comment]
Issue completed by @jhsanchez26 .
