### ISSUE TITLE
User profile page - setting page creation 

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#217]
**Objective:**
Create a new setting page for a user profile
**Task Description:**
This page is going to include a change password, change profile, picture change, username, and finally a change email. There is an existing profile symbol on the home page and we will add more to it. 
**Implementation:**
We start by creating a new page and implementing similar work with the previous pages. This portion is only going to be the front-end aspect. we create fields for each of the options mentioned above.
Subtasks:
future tasks are as follows: adding functionality to change profile picture, adding functionality to change username and password, adding functionality to change email, and finally making the default profile picture with the user's first letter of their username. 
**Testing and Debugging:**
For this task specifically, we can test by launching the new page and see if there's an action occurring when clicking on the profile symbol 
**Deadline:**
April 20, 2024

**Comment by evnd04** [comment]
When you talk about adding functionality, describe the specific functionality that will be added. Example:

"adding functionality to change profile picture" should be changed to "Add the ability for any user to change their profile picture" And all this should be added to terminology in the documentation describing each aspect of the feature.

**Comment by Saul-Caban-UPRM** [comment]
Alright, I've edited the issue applying what was said in the previous message.

**Comment by jhsanchez26** [comment]
Settings page was successfully created. So far, it has a working link directly from the home page to get to it, as well as the front end implementation of the change username and change password functions.

**Comment by Javi510348** [comment]
The issue was completed by @1uismar33r0 and @jhsanchez26 .
