### ISSUE TITLE
Pet Gender and Age - Pet Listings

### ISSUE THREAD

**Issue by JohnSantiagoRuiz** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#22]
This feature can be implemented as one of the first filtration systems for the pet listing section. With this feature you can select the gender or/and the pet's age. That way it's more suitable for the adopter to find the pet they want.

**Comment by evnd04** [comment]
I agree with this feature, so users have control over what pets they see and choose for adoption.

**Comment by rukitoyordan** [comment]
@JohnSantiagoRuiz same here, what is the status of this task? Please let me know!

**Comment by JohnSantiagoRuiz** [comment]
@rukitoyordan this task is being worked on currently. The assignees are Raquel Quiñones and Alexis.

**Comment by rukitoyordan** [comment]
@RaquelQuinones and @AlexisTraversoPR, please make sure to properly describe this task in a detailed manner. 

To quote the professor: 
> it's the responsibility of the managers not to assign tasks that are not yet sufficiently well defined AND it's the developers' responsibility not to take any tasks that are not yet well enough defined. For milestone 3, I will not accept tasks that, at the end of the milestone, are as insufficiently defined as this. The developer will not get the score and the manager's score will also be affected.

**Comment by RaquelQuinones** [comment]
@rukitoyordan @evnd04 @JohnSantiagoRuiz 

To implement the Pet Gender and Age feature as one of the primary filtration systems for the pet listing section, we would incorporate checkboxes for users to select their preferences. Within the website structure, we would introduce filters specifically for gender (male, female, or unspecified) and age range (such as puppies, young, adult, and senior). Upon selection, the backend logic would filter out pets that match the chosen criteria, displaying only those that meet the user's specifications. This implementation enhances the user experience by allowing adopters to efficiently find pets that align with their preferences, facilitating smoother adoptions and increasing the likelihood of successful matches between pets and owners. Additionally, clear labeling and intuitive design elements would ensure ease of use for visitors navigating the website.

**Comment by RaquelQuinones** [comment]
Filtration systems for the pet listing section is done.
