### ISSUE TITLE
[Lecture Topic Task] Sequence Diagram - CTA Buttons Homepage Website Management Team 🚦

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#224]
**Task**: Create a sequence diagram for implementing call-to-action buttons on the
homepage that will be worked on by Website Management Team and Managers.

> The purpose of this task is to generate a sequence diagram for describing Homepage behaviors. This will be worked as a Lecture Topic Task in conjunction with all Web Management and Managers.

**Description**: 
Your task as part of the Website Management team is to develop a sequence diagram for implementing call-to-action buttons on the adoption website's homepage. 

These buttons will serve as essential entry points for users, encouraging them to take specific actions related to adoption, donation, volunteering, and learning more about the adoption process. 

The sequence diagram should depict the steps involved in designing, integrating, and positioning the call-to-action buttons effectively.

**Resources**:
[sequence-diagrams.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999767/sequence-diagrams.pdf)

**Deadline**: April 19th, 2024

**Comment by GiovanniMaysonet** [comment]
Could we move the deadline for this to the 22nd? It seems we might have had some drawbacks

**Comment by evnd04** [comment]
Yes, describe the drawbacks had if possible in a comment.

**Comment by Adriana-Isabel** [comment]
Sofía: Button Request **DONE**
Adriana: Button Design **DONE**

**Comment by smbv** [comment]
https://www.figma.com/file/ou6lIt74yn2KfRJqfSXowJ/LTT%3A-Sequence-Diagram---CTA-Buttons-Homepage?type=whiteboard&node-id=0-1&t=9nkoz1cG0rFYHR8H-0
