### ISSUE TITLE
[Lecture Topic Task] Sequence Diagram - Pet Registration Feature for Pet Interfaces 🏺

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#225]
**Task**: Create a sequence diagram for the "Pet Registration" feature.

> This will be worked as a _**Lecture Topic Task**_ in conjunction with all Pet Interfaces.

> The purpose of this task is to generate a sequence diagram for describing Homepage behaviors. This will be worked as a Lecture Topic Task in conjunction with all Pet Interfaces.

**Description:** 
As part of the Pet Interfaces team, your task is to design a sequence diagram that illustrates the interactions and flow of events involved in the "Pet Registration" process. 

This includes capturing the steps required for pet owners or administrators to register a new pet onto the adoption website. Consider the interactions between the user interface, backend systems, and database to ensure a seamless registration process. The sequence diagram should outline the steps involved, such as entering pet details, uploading photos, and submitting the registration form. 

Pay particular attention to error handling and validation checks to ensure data integrity and a user-friendly experience.

**Resources**:
[sequence-diagrams.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999767/sequence-diagrams.pdf)

**Deadline**: April 19th, 2024

**Comment by Alej24** [comment]
I have this task finished locally, will add to the m3 documentation soon.

**Comment by rukitoyordan** [comment]
@Alej24, if you are able to send a link of it here too that would be great for documentation purposes here in GitHub!

**Comment by Alej24** [comment]
![pet registration sequence](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/99218281/74cebeb8-7806-48a3-a5e4-1a31b74b7ffe)
