### ISSUE TITLE
[Lecture Topic Task] Sequence Diagram - User SignUp Feature for Human Interfaces ⚔️

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#226]
**Task:** Create a sequence diagram for the "User Signup" feature.

> This will be worked as a _**Lecture Topic Task**_ in conjunction with all Human Interfaces.

**Description:** 
Your task as part of the Human Interfaces team is to develop a sequence diagram for the "User Signup" feature of the adoption website. This diagram should depict the sequence of interactions between users and the system during the signup process. Consider the various steps involved, including entering personal information, selecting a username and password, and agreeing to terms and conditions. 

Ensure that the sequence diagram accurately represents the flow of events and interactions between the user interface, backend systems, and database. Pay attention to error handling, validation checks, and user feedback to create a smooth and intuitive signup experience.

**Resources**:
[sequence-diagrams.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999767/sequence-diagrams.pdf)

**Deadline**: April 19th, 2024

**Comment by jhsanchez26** [comment]
I worked on the explanation for the login sequence diagram.

**Comment by 1uismar33r0** [comment]
I re-did the sequence diagram to be up to date with the Signup system and added the description for the diagram
