### ISSUE TITLE
[Lecture Topic Task] Petri Nets - User Adoption Journey for Human Interfaces 🪭

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#227]
**Task:** Create a Petri Net for the “User’s Adoption Journey” within the app

> This will be worked as a _**Lecture Topic Task**_ in conjunction with all Human Interfaces.

**Description:** 

Create a Petri Net Diagram focusing on the user journey through the app, from sign-up to adoption. Highlight key interactions such as searching for pets, interacting with pet profiles, setting up appointments, and completing adoption paperwork. 

The diagram should also consider user support processes, notification systems for updates on favorite pets, and feedback mechanisms post-adoption to ensure a user-friendly experience (essentially basing on what is built so far).

**Resources:**
[Petri-nets.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999985/Petri-nets.pdf)
[Petri Net Examples-20240416.zip](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999986/Petri.Net.Examples-20240416.zip)

**Deadline:** April 22nd, 2024

**Comment by Javi510348** [comment]
We drew the Petri Nets of the User interaction in the website using Snoopy 2. We did 2 Petri Nets in which one of them represents the interaction of a regular user and one for the Admin user. To be able to confirm if the Petri Nets were correct, we used the animation mode in Snoopy 2, so we could see the logic applied to the Petri net. 

Once the Petri Net was completed, we added them to the documentation for further explanation.
