### ISSUE TITLE
[Lecture Topic Task] Petri Nets - Pet Adoption Process for Pet Interfaces 🧸

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#228]
**Task:** Create a Petri Net for the “Pet Adoption Process” within the app.

> This will be worked as a _**Lecture Topic Task**_ in conjunction with all Pet Interfaces.

**Description:** 

Develop a Petri Net Diagram that maps out the entire journey of a pet within the app, from being listed for adoption to the adoption process. This should include all potential interactions a pet can have with the system, such as health check updates, scheduling meet-and-greets, and status updates (available, pending, adopted). 

Focus on ensuring the process is seamless and includes all necessary steps to maintain the pet's wellbeing and streamline the adoption process.

**Resources:**
[Petri-nets.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999985/Petri-nets.pdf)
[Petri Net Examples-20240416.zip](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999986/Petri.Net.Examples-20240416.zip)

**Deadline:** April 22nd, 2024

**Comment by JohnSantiagoRuiz** [comment]
Task is complete and has been added to the documentation.
