### ISSUE TITLE
[Lecture Topic Task] Petri Nets - Website’s Structural Interactions for Web Management 🦑

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#229]
**Task:** Create a Petri Net for the “Website’s Structural Interactions” within the app.

> The purpose of this task is to generate a Petri Net for describing Homepage behaviors. This will be worked as a Lecture Topic Task in conjunction with all Web Management and Managers.

**Description:** 

Construct a Petri Net Diagram that outlines the backend processes supporting the app, including possible database management, user and pet data synchronization, security checks, content management systems, and analytics tracking. 

This diagram should detail how different components of the website interact with each other and with the frontend to ensure smooth operation, data integrity, and scalability (You can also focus on web logistics).

**Resources:**
[Petri-nets.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999985/Petri-nets.pdf)
[Petri Net Examples-20240416.zip](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/14999986/Petri.Net.Examples-20240416.zip)

**Deadline:** April 22nd, 2024

**Comment by smbv** [comment]
https://www.figma.com/file/okRfzypGtULhRbx7oRaVfB/petri-nets---LTT?type=whiteboard&node-id=0-1&t=4flxitUVEkf6220u-0
