### ISSUE TITLE
[Lecture Topic Task] Risk Analysis - Pet Interfaces UML Model 🐛

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#231]
**Task:** Create a Risk Analysis evaluation on potential risks associated with the Pet Interfaces section of our project. 

**Description:**

> Implementing UML (Unified Modeling Language) models is a highly effective strategy for system and software development, including for web applications like a pet adoption site. UML provides a standard way to visualize system architecture, including aspects such as system components, behavior, and interactions.

Identify Risks: Start by listing potential risks associated with Pet Interfaces, such as inaccurate pet data, unresponsive filtering options, and issues with pet profile updates. Use scenarios to highlight how these risks could impact both the user experience and the pet's adoption chances.

Visualize with Risk Matrix: Create a risk matrix to categorize these risks based on their probability and impact. Utilize tools like Microsoft Excel or Google Sheets to make the matrix visually engaging. Incorporate colors to differentiate between levels of risk severity.

Design Risk Diagrams: Use graphical tools to create risk diagrams that map the flow of interactions within Pet Interfaces, indicating where potential risks might occur. This can be done using software like Lucidchart or Microsoft Visio.

### Some types of Diagrams that can be done (optional but helps with visuals)

Activity Diagrams: These diagrams are useful for modeling the workflow of various components of the system by showing the flow from one activity to another. This could include the flow of navigating through the site or the steps involved in processing an adoption.

Tools: Use UML tools like Creately, Lucidchart, or IBM's modeling tools to draw your diagrams and maintain them.

**Resources:**
[Risk Analysis.pdf](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/files/15000381/Risk.Analysis.pdf)
https://creately.com/blog/diagrams/uml-diagram-types-examples/
https://venngage.com/blog/uml-diagram-examples/
https://bigpicture.one/blog/project-risk-assessment-examples/

**Deadline:** April 22nd, 2024

**Comment by Christian2101** [comment]
![Screenshot 2024-04-25 191343](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/90163881/52237334-2638-4529-b3e4-bbce058cbdb7)

Finished creating the Risk Matrix, continuing now to create the Risk Diagram

**Comment by Christian2101** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/90163881/b756805f-ff77-40ec-acf8-b11a6ec29e41)

Finished creating the Risk Diagram, will add to the m3 documentation soon.
