### ISSUE TITLE
Fixing and Revising Documentation Section 2.1.2 (Terminology)

### ISSUE THREAD

**Issue by ErickCruz4** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#234]
Task: Revise and fix Section 2.1.2 of the Documentation

Description:
As part of the Human Interfaces team, I was tasked with revising section 2.1.2 of the adoption website documentation. This section provides essential terminology, actions, events, and behaviors related to the adoption process. The revision aims to align the content with the feedback received from the professor and ensure clarity and accuracy in the descriptions.

The revised section will focus on:

Terminology: Clear definitions for terms like "Pet," "Shelter," "Adoption Form," and "Foster."

Actions: Detailed explanations of actions such as "Pet Profile Creation," "Filling Out Adoption Form," "User Signup," "Verification," and "Pick Up."

Events: Descriptions of key events like "Pet Added," "Selection," "Form Submission," and "Approval."

Behaviors: Insights into behaviors such as "Adopting" and "Fostering."

The goal is to provide a comprehensive and concise overview of the adoption process, ensuring consistency and accuracy in terminology and descriptions. This revision will enhance the understanding of the adoption process for both internal team members and external stakeholders.

Deadline:
April 19th, 2024

**Comment by rukitoyordan** [comment]
This issue will be expressed on #235.
