### ISSUE TITLE
M3 Documentation Centralized Task for Documentation Team ⏰

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#235]
**Task:** This is a centralized task specifically for the Milestone 3 Documentation Members who will work more intensively on the documentation. This does not mean that they will not continue with their tasks or that the rest of the team members are exempt from helping out. The Milestone documentation is the responsibility of everyone in the project. 

**Description:**
Below will be some comments on good documentation practices, as well as the feedback from the professor and the specifics on what we did not meet properly that need to be met for the betterment of our Milestone gradings.

**Deadline:** April 25th, 2024

**Comment by rukitoyordan** [comment]
**Feedback from the professor on what needs to be worked on/fixed**

> The needs should not be "app specific", i.e. they should not be tied to the fact that the solution is an app. When you speak of users and user-friendliness then you have already connected the needs that people face out there in the world with a specific way of satisfying those needs, namely an app. Now, it's clear that you want to implement an app in the end, but at this stage in the documentation we want to not tie the needs people face to a specific way of satisfying them. Think "what" not "how". If there are no users yet, then who do we talk about? We have the possible adopters, we have the fosters, and we have people working/volunteering for RUMAR. These different groups of people might actually have quite different needs/wants. Thinking about them independently of the app can lead us to better understanding of their needs than if we would just think about them as "users". The good news is that your needs statements are not that tangled with the app that they could not easily be redone.
> 
> You can check your ideas by asking "which need does this help satisfy?"
> 
> In the derived goals section, you do not want to show goals that are already implied by your primary goals as captured in the current situation, needs, and ideas. So, that you have to do domain exploration is not anything that is derived: it's quite in line with what you need to do to attain your primary goals. Same for customization of user profiles to enhance user engagement and satisfaction. This would seem to be part of your primary goals and not a derived goal.
> 
> Much of what I write for this submission I have already written as comment on the previous submission.
> 
> When you're talking about something that implies the existence of the system-to-be - e.g. "The website enables users to log in or sign up for an account to access its features." - then that's clearly a sign that you're not talking about the domain, and so also not about domain rough sketch. Also, your rough sketch does not seem very rough: e.g. "The process starts with filling out a form that will determine the viability for the client to adopt a pet. After filling in the documentation, the client will now browse the selection of pets that the shelter offers and then select the desired pet based on their preferences." that's already very processed and not rough at all. We want to start out with a rough sketch for a reason: only if we really start from the rough sketch can we make the steps taken explicit and only if the steps are explicit can we retrace them later either to verify that we drew the right conclusions or - when additional knowledge has been obtained - to see whether they can also accommodate that new knowledge. For domain rough sketch statements we would often have stories that have happened to a person with very specific detail like "last Wednesday Carl went to the shelter to adopt Miss Cheivous, a female gray short hair tabby currently aged 3 months..." then we hold several such statements side-by-side and identify the more abstract concepts that we think we should use going forward.
> 
> Your terminology lacks some terms: for example "adopter", "shelter staff", "volunteer",...
> 
> If you use a single terminology for all the terms around your project, then you have to tag the terms with the most abstract development phase that would introduce the term. For example, "pick up" is something that's relevant at the domain level already and so we tag it "domain", but, say, sign in only becomes necessary since we have decided to have a system on which there are several accounts and we need to manage sessions, so we tag it "application", because only since we have decided to implement an application does this become necessary.
> 
> Be more careful with the wording for the events: in "selection", "form submission", and "approval" we could misunderstand it to mean the action instead of an event. For example, what you write for selection would be seen as the process of selecting instead of as the moment the person has just selected. One is the action, the other is an event.
> 
> When you describe a behavior you want to make it clear that it is composed from actions and events. In your behaviors I can only see actions.
> 
> You already have a terminology further up, why another here? The first three bullet points do not define any terms. The title is "DOMAIN terminology", but then you talk about "within the context of our application": the application does not belong to the domain. Also, from the perspective of the domain something like "adoption" involves transfer of responsibility to care for the animal...
> 
> There's duplication in the bullet points on rescue, foster, adoption, and donation that are above the heading "analysis and definition" and the ones that come below.
> 
> Function signatures are used to abstract away some detail for actions/operations in the domain. They focus on the kinds of things/concepts that a operation needs and what it will generate. This was discussed in class. So, for example, we could conceive of the shelter as having a collection of animals that can be adopted and we can therefore introduce an operation adopt(Shelter, Animal, Adopter): (Shelter, Adopter) and discuss that, the way we understand this operation, the act of adopting takes a he Shelter from which the Animal is adopted. It also takes an Adopter who will be the future caregiver. The operation results in a pair of a Shelter and an Adopter since the Shelter, after successful adoption, has that Animal less and, if we assume that from the Adopter we can observe all the Animals in their care, the Adopter must have changed as well in a successful adoption. What the right signatures are depends on the way you think about the domain and the operations that take place within it, so there's not a RIGHT way to think about the signatures. There is just a description of what you think how the domain "hangs together" and function signatures that are or are not consistent with that description.
> 
> Signing up takes a person doing the signing up and also it's not instantaneous. Both strong indicators that we're talking about an action and not an event. This action will then trigger an event: for example, "a prospective adopter has just completed their sign up". Go over the other events as well and check that they clearly are events and not actions. Also, some of the events that you list are from the domain others are not. It's okay to have them both in the same terminology, but then you have to say from where they come. Moreover, events, actions, and behaviors belong together with the entities: all of these are concepts/terms that need to be defined. That's what the terminology is for. This was discussed in class!
> 
> Sorry, but what you write about personas does not seem to have anything to do with what we talked about in class.
> 
> The user-friendly interface: that's not what is meant by interface requirements. Interface requirements are concerned with prescribing properties of the way in which observable phenomena from the world out there become data inside the machine and vice versa. So, for example, "whenever a pet is not available for adoption and a potential adopter visits the pet's page, the system must display that page with a red background." This would be an interface requirement: how is the information about pet availability for adoption communicated into the world out there?
> 
> We talked about requirements and how they need strong, binding language. In particular, "should" is a word to avoid in connection with requirements: it's just not requiring enough. When something "should" be done it implies that it's not necessary, just desirable. However, a requirement must be satisfied, it's not optional. You use "should allow" that makes it even weaker: even "must allow" is not a suitable requirement. An adversary developer might say: "we're not forbidding it, so we're allowing it, so we're satisfying the requirement."
> 
> Machine requirements are under the heading domain requirements: they do not belong here.
> 
> Real-time is a very strong term, make sure that you are requiring the right thing: how soon after a change in the availability does the status in the system really have to be updated? You certainly do not require that to happen, say, within 1ms of the change out there in the world...
> 
> Make your requirements much more specific!
> 
> If you cite normal operating conditions then you have to define them somewhere.
> 
> "Concurrent" could be interpreted as e.g. all concurrent scenarios update information in the exact same microsecond. Providing for this form of concurrency might lead to overprovision, since you do not really need that level of e.g. response time. That's why we require something more along the lines of: "when concurrently running 300 normal scenarios (of the kind potential adopter) that all randomly start within a 5 minute interval, then in 99% of all these scenarios will face response times of at most 2 seconds"
> 
> "The system must be able to run in a desktop web browser" a lazy developer might take this to be satisfied if the runs in one (e.g. Firefox 123.0.1 64-bit on Linux) desktop web browser and a demanding client might take this to be satisfied if the system runs in any (=all) desktop web browser. Of course, both are unreasonable.
> 
> What do you want to illustrate with your diagrams? Remember - this was said repeatedly - that diagrams are only useful inasmuch as they make it easier to bring across a point that you want to make. The diagrams are not even referenced.
> 
> What you claim to be domain rough sketch on page 20 has nothing to do with domain rough sketch. Review what domain rough sketch is.
> 
> Give examples of the verification and validation activities that you carried out. For example, if you consistently apply and define terms used in your project, then you can report on conversations during which you found a missing term and how you decided to define it. Similarly, you can give examples of user acceptance tests that were carried out, what the result of the test was. Which scenarios you have walked through with your stakeholders, what new invites you gained,...

**Comment by rukitoyordan** [comment]
**Insight on the Grading Criteria and how it was evaluated for M2**
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/123176121/6b520fbc-41df-43ff-8187-e26447773563)

**Comment by rukitoyordan** [comment]
**M3 Evaluation Guidelines and Criteria**
                        ━━━━━━━━━━━━━━━━━━━━━━━
                         EVALUATION GUIDELINES

                          Marko Schütz-Schmuck
                        ━━━━━━━━━━━━━━━━━━━━━━━





These guidelines will be used to evaluate each project's documentation
submission. The whole project has now culminated, so we do want to see
some type of _completeness_. In terms of features, completeness means
that there is a minimal collection of features that make the application
viable. Completeness also refers to the other activities on the project
(domain description, requirements prescription, software architecture,
design, testing, …). For example, does the team document the
requirements of the features that are implemented? Are the phenomena
from the domain that the requirements refer to fully described? Does the
team use automated tests for their features? The guidelines and examples
are more detailed than what would easily fit into the format of rubrics,
so the guidelines are stated separately and the rubrics then are quite
generic.

• Changes to the previous submission must be clearly visible. Use a
  different background color, change bars in the page margin, or other
  ways to clearly indicate the changes.
• The log book gives an overview of the changes (but not the full
  changed content) since the last submission.
• The actual changes, new developments, etc are integrated into the
  overall document.
• All the criteria where the previous submission did not follow the
  guidelines have been improved.
• Any additions and changes follow the guidelines already established
  for the previous submissions.
• Completeness of the other development phases: domain description,
  requirements prescription, design, … For example, requirements for all
  the features that have been implemented are also documented. All the
  terms that are used to formulate the requirements are clearly defined
  in a terminology, …
• Application of topics, techniques, tools, methods, … from the
  lectures:
  • domain engineering and domain facets
    • stakeholders

      The team identifies and describes (domain and requirements)
      stakeholder groups that are relevant for the project.

    • personas

      The team has developed personas that are detailed beyond merely
      their user-stories, so the persona really comes alive.

    • domain facets

      The team has explored relevant domain facets. For example, in a
      project concerned with supermarket checkout a team might want to
      talk about scanning devices (support technology). But that team
      might not have anything to say concerning the scripts
      facet. Relevance needs to be considered in the assessment. Teams
      should demonstrate that they can judge relevance and not create
      filler.

    • business processes

      The team describes at least one relevant and substantial business
      process from the domain for each stakeholder group.

  • Petri nets

    The team uses Petri nets (place transition nets) to model competing
    processes that access common resources. It's not necessary to have a
    complete model but we want to see at least some are competing
    activities.

  • requirements
    • domain requirements

      The team identifies domain requirements from domain
      properties. For example, in a project concerned with libraries,
      books, borrowing, … there is a domain property that every book has
      an owner. When the team then moves on to determine requirements
      and the focus is only on libraries (not e.g. the books a patron
      might otherwise own), we get a domain requirement: the
      system-to-be must associate with each book exactly one library as
      the owning library.

    • interface requirements

      The team analyzes and documents the shared data initialization and
      update requirements, the man-machine and the machine-machine
      dialog requirements, and the physiological requirements.

    • machine requirements

      The team identifies and documents relevant machine requirements
      (performance, availability, accessibility,…).

  • software design

    The team analyzes the requirements and identifies and documents
    components that collaborate to satisfy the requirements. There is at
    least one major business process that the team uses as a scenario to
    validate the design.

  • risks

    The team goes through at least one risk analysis cycle. The cycle
    consists of risk identification, risk assessment, countermeasure
    exploration, and countermeasure evaluation. The risk analysis cycle
    results in new or changed requirements. The project's documentation
    includes corresponding descriptions and justifications for
    estimates.

**Comment by rukitoyordan** [comment]
### 🚨🚨 IMPORTANT M3 EVALUATION GRADING 🚨🚨
This is essentially what needs to be taken into consideration fully.
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/123176121/6d4b78a8-eebf-4541-85a2-460f8c7d264f)

**Comment by ErickCruz4** [comment]
Task: Revise and fix Section 2.1.2 of the Documentation

Description:
As part of the Human Interfaces team, I was tasked with revising section 2.1.2 of the adoption website documentation. This section provides essential terminology, actions, events, and behaviors related to the adoption process. The revision aims to align the content with the feedback received from the professor and ensure clarity and accuracy in the descriptions.

The revised section will focus on:

Terminology: Clear definitions for terms like "Pet," "Shelter," "Adoption Form," and "Foster."

Actions: Detailed explanations of actions such as "Pet Profile Creation," "Filling Out Adoption Form," "User Signup," "Verification," and "Pick Up."

Events: Descriptions of key events like "Pet Added," "Selection," "Form Submission," and "Approval."

Behaviors: Insights into behaviors such as "Adopting" and "Fostering."

The goal is to provide a comprehensive and concise overview of the adoption process, ensuring consistency and accuracy in terminology and descriptions. This revision will enhance the understanding of the adoption process for both internal team members and external stakeholders.

Deadline:
April 19th, 2024

**Comment by GiovanniMaysonet** [comment]
I have worked on and finished the documentation sections 1.3 (1.3.1 and 1.3.2)
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/99d4729b-4090-4fe4-8158-ef373abb579e)
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/68f1e9b3-d991-4da5-8e92-2a9c9a20b9d4)
Though this work is still up to be revised and modified I believe to have developed it to satisfactory results.

**Comment by yamayrie** [comment]
I have added information in 2.1.6 function signatures about get route for pet listing page, post route for adoption form page, and post route for faculty page. 
![Screenshot (6)](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/124181645/828bb758-c2b1-453f-b072-304245019e43)

**Comment by frances-sepulveda** [comment]
I have added new descriptions for the past diagrams. 
<img width="919" alt="Screen Shot 2024-04-26 at 12 41 57 PM" src="https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/124540089/99dcffa6-203a-41ce-953e-417906c56837">

**Comment by frances-sepulveda** [comment]
I have added two new diagrams (petri nets) , and I have describe them completely. 

<img width="848" alt="Screen Shot 2024-04-26 at 12 43 40 PM" src="https://github.com/uprm-inso4101
<img width="839" alt="Screen Shot 2024-04-26 at 12 44 10 PM" src="https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/124540089/74690bdf-7b3f-440f-ab7f
<img width="861" alt="Screen Shot 2024-04-26 at 12 44 29 PM" src="https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/124540089/27a6a54e-8789-4757-9481-5999e6efac57">
-9dec5a73b7fd">
-2023-2024-s2/semester-project-rumaradoptionapp/assets/124540089/622b3f88-b6c3-4c82-b754-44e2b69f66d2">

**Comment by GiovanniMaysonet** [comment]
Modified and reworked Personas according to professor's criticisms:
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/54a09b6b-0731-4f4f-9b8a-900be3e62101)
Will continue to edit them.

**Comment by yamayrie** [comment]
Reworded sentences in interface requirements. These are the final changes to the sentences:

- The system must include a view for management and/or shelter staff to update the availability of the pets.
- The system must provide users a way to view and edit their profile information. Some of the information available for change could be the password, email, name, etc.
- The system must provide a way in which shelter staff can register new pets to the website and to their specific shelter.
- The system needs to enable users to bookmark pets they find interesting.
- The system must have a notification section in which it will communicate to the user if there is a decision on a specific item in which it will confirm the validation of the email.
- The system must facilitate easy management for handling the database, enabling modifications to be made as necessary within pets, shelters, and/or users.
- Users must be able to complete adoption forms if they wish to adopt a specific animal within the system.
- Shelter staff must have access to the forms within the system to update their statuses based on their conclusions about potential adopters.

**Comment by JohnSantiagoRuiz** [comment]
Task: Revise/fix documentation.

Description:
As part of the Pet Interfaces team, I was tasked with revising/fixing parts of the documentation. Specifically I revised/fixed the followings parts:

- Domain Facets
- Machine Requirements
- Validation and Verification
- Secondary Goals 
- Lecture Topic Tasks assigned to Pet Interfaces. 

The goal of revising the documentation for the Pet Interfaces team is to enhance the clarity, accuracy, and coherence of the materials. This ensures that all aspects of the project are aligned with the feedback provided by the professor. Ultimately, this effort aims to optimize understanding and facilitate smoother implementation of the project's objectives.

**Comment by yamayrie** [comment]
Added description for lecture topic task regarding the pet registration sequence diagram
![Screenshot (9)](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/124181645/93c91995-5433-4717-b97d-d477fc577191)

**Comment by yamayrie** [comment]
Revised concept analysis. I determined that there were no changes needed and the concept remains suitable in its current form. Could be re-examined.

**Comment by GiovanniMaysonet** [comment]
Worked on and modified section 1.5 with the exception of one part:

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/a8d1d50d-7a99-457a-8d8b-1610efbd17e4)
