### ISSUE TITLE
Adding pet Images feature

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#241]
A new table Pet Images has been created to manage all images for pets on the website. The goal of this feature is to be able to add and remove images from the table with ease. This will be done through the pet profiles page, for those with faculty access. 

The feature will be classified as complete when images can be added and removed from the table.

**Comment by evnd04** [comment]
Use the task template to be approved.
