### ISSUE TITLE
Creating functions for Pet Images table

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#242]
Objective:
add the function to fetch images from the new pet images table

Task Description:
A new table has been created with the purpose of managing all pet images for the website. The new table requires function to fetch and retrieve the data on it. 
Specifically:
-adding images
-removing images
-getting images

Implementation:
This feature would be implemented by creating a get, add and remove image function in the backend. Similar to those function we use to manipulate the pet data.

Subtasks:
-create add image function
-create remove image function
-create get image function
-create get all pet id image function

Testing and Debugging:
feature will be tested using the pet profiles page, using it picture album feature to see if images appear, and if the album is updated when images are added/removed.

Deadline:
4/22/2024 11:59pm

**Comment by evnd04** [comment]
Use the task template to be approved.

**Comment by Alejandro-DeJesus** [comment]
Updated task description to use task template

**Comment by evnd04** [comment]
Approved

**Comment by Alejandro-DeJesus** [comment]
This task is complete, the ability of getting images for display in pet listings and pet profiles is functional and working as intended,
