### ISSUE TITLE
Remember Username Feature

### ISSUE THREAD

**Issue by frances-sepulveda** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#244]
Objective:
The objective of this feature enhancement is to implement a "Recover Username" feature that allows users to retrieve their forgotten usernames securely and seamlessly. This feature aims to improve user experience and provide better support by offering users a straightforward process to recover their usernames associated with their accounts.

Task Description:
This task involves designing and implementing a "Recover Username" feature that guides users through the process of retrieving their forgotten usernames. The feature should be user-friendly, secure, and accessible to all users, regardless of their technical proficiency.

Implementation:
1. User Interface:
   - Create a dedicated web page or modal window for the "Recover Username" feature.
   - Design a user-friendly interface with clear instructions and input fields for users to enter information required for username recovery.
   - Include descriptive labels and placeholders for input fields (e.g., email address, phone number) to guide users through the recovery process.

2. Input Validation:
   - Implement client-side and server-side input validation to ensure that users provide valid information for username recovery.
   - Validate input fields such as email address or phone number to prevent errors and ensure the accuracy of the recovery process.

3. Username Retrieval Process:
   - Upon submitting the recovery form, verify the provided information against the user database to identify the associated username.
   - If the provided information matches the records, display the retrieved username to the user on the confirmation screen.
   - If the provided information does not match any records, display an appropriate error message and prompt the user to try again or seek further assistance.

4. Security Measures:
   - Implement security measures to protect user information during the recovery process, such as encryption of sensitive data and secure transmission protocols.
   - Use CAPTCHA or other verification methods to prevent automated attacks and ensure that the recovery requests are legitimate.

5. Notification:
   - Optionally, send a confirmation email or SMS message to the user's registered email address or phone number upon successful username recovery, providing additional security and assurance.

6. Accessibility:
   - Ensure that the "Recover Username" feature is accessible to users with disabilities, including those using screen readers or assistive technologies.
   - Test the feature using accessibility tools and guidelines to identify and address any accessibility barriers.

Testing and Debugging:
1. Conduct thorough testing of the "Recover Username" feature across different browsers, devices, and screen sizes to ensure compatibility and responsiveness.
2. Test various scenarios, including valid and invalid input, to verify the accuracy and robustness of the username recovery process.
3. Debug any issues or errors encountered during testing, such as incorrect username retrieval or validation failures, to ensure a smooth user experience.
4. Document the testing process and any identified issues, and track their resolution to ensure the successful implementation of the feature.

deadline:
April 24, 2024

**Comment by rukitoyordan** [comment]
Remember to use the proper task template for it to be approved

**Comment by evnd04** [comment]
When possible add a deadline, but its approved
