### ISSUE TITLE
User profile logo-Fixes and improvements

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#249]
Objective:
Check if the user is logged before showing the users profile. Additionally fix the drop down boxes that cause the user logo to move every time the user clicks on the logo. 
Task Description:
Currently the profile logo appears in the home page without checking if the user is logged, we have to make sure that the use doesn't access the user profile, by using the login session should prevent this problem. Finally fixing the position of the logo
Implementation:
For the position of the logo is quite simple, simply edit the section of style in "home.ejs" file specifically the ".dropdown function and set a format for it by slowly modifying the positions of the button for the profile logo.  For the login session we would edit the "index.js" file and change the function under the "Route" and add "loggedIn: req.session.user_id". with these changes we should be able to fix two bugs
Testing and Debugging:
By checking the position of the profile logo should tell us if does work, and loading up the page and login into it should tell us the if the login session is working. 
Deadline:
April 21, 2024

**Comment by evnd04** [comment]
Approved
