### ISSUE TITLE
Database Creation

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#25]
This task will be crucial for the development of the project. The database will be used for any of the required for the project. The hosting service for our Database is called Supabase in which they offer free development databases for small projects. Our database will be using PostgresSQL.

**COMMENTS**

- An invitation to the team in Supabase will be sent once the database has been created.
- If you need more privileges with the database, please let me know. 

Due Date: 02/12/2024

**Comment by Javi510348** [comment]
The database has been created in SupaBase. The database will be using PostgresSQL since it's the only one available for the SupaBase.

SupaBase was selected because it will help us have a better view on how our data is being stored by using the "Table Editor" section. Also, it provides us with a "SQL Editor" that it will help us test our queries before they are implemented in our code. SupaBase has many features including a "Schema Visualizer" to be able to see the relation between tables.

This is my first time working with Supabase, so there are still some things that I need to learn about it. For further information, check the links below.

https://supabase.com/docs

https://supabase.com/docs/guides/database/overview      (**IMPORTANT**)

https://www.postgresql.org/docs/current/

https://www.postgresqltutorial.com/

https://www.restapitutorial.com/lessons/httpmethods.html

**Comment by Javi510348** [comment]
People who are going to work with the creation of tables for the database, please send me a message with your email since the platform that is going to be used does not allow me to share the same link for everyone. The database is located in Supabase.

**Comment by rukitoyordan** [comment]
@Javi510348 if the database has been created let me know to close this issue

**Comment by Javi510348** [comment]
@rukitoyordan The database has been created, we can close the issue.
