### ISSUE TITLE
Milestone 3 Presentation Attribution - Human Interfaces Team 🕍

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#256]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Human Interfaces team towards the proper documentation and development on the **_Milestone 3 Presentation_**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, April 26 2024 @ 1800** 🚨

**Comment by frances-sepulveda** [comment]
I have written new descriptions for de past and new diagrams.

**Comment by jhsanchez26** [comment]
I worked on the future implementations slide and added speaker notes for the person giving the presentation.

**Comment by Javi510348** [comment]
I worked with the achievements slide. We talked about specifically about the most important achievements throughout the project.

**Comment by yamayrie** [comment]
I worked on the documentation slide. I have added information regarding areas improved and added speaker notes.

**Comment by ErickCruz4** [comment]
Worked on the Risk Assessment slide completely. Also worked on the other documentation slide. Added speaker notes for the Risk Assessment slide. In the other slide I added the bullets that have to do with Terminology and Actions.

**Comment by Angel-Rosado** [comment]
Worked on the second Achievement slide. It explains the most important features that were worked regarding users interfaces, and added a note that explains it for the speaker.

**Comment by jhsanchez26** [comment]
I worked on the sign up page slide and log in page slide as well as added speaker notes for both.
