### ISSUE TITLE
Code Integration with Database (Backend)

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#26]
Once the database is created, we will need to integrate the database with our code. To make this possible, we will be using python flask,python  flask-cors and psycopg2-binary). Flask and Flask-Cors  will be used, so we can have a web framework in python for our project. Psycopg2 is necessary, so we can use our code with the database by using postgresSQL. Also, a simple file structure for the backend will be created. All of the necessary "libraries or modules" will be available in a requirements.txt for so we can have the same versions of libraries and modules across different devices.

Due Date: 02/13/2024

**COMMENTS**

- Everything could be subject to change if better options are recommended.
- If you wish to cooperate with this task, please let me know.

**Comment by rukitoyordan** [comment]
@Javi510348, love this initiative. I recommend you try to maybe try to find resources in regard to PostgreSQL and PythonFlask. Seeing that making a Database is not easy at all, I don't expect it to be done for this first Milestone, but if you think it can be done by then I will make sure to grade it accordingly. 🩷

**Comment by rukitoyordan** [comment]
I also recommend splitting this task into more bite-sized ones!

**Comment by Javi510348** [comment]
File Structure:

backend
    |
    |
    - __init__.py
    - app.py
    -src
        |
        |
        -config (Responsible of storing database information)
        -controller (Manages the data received from the database)
        -dao (pattern that provides an abstract interface to the database)


Instructions for Development:

- Make sure that the latest version of Python is installed in your computer.
- In VScode, install the Python Extension. It should include Pylance and Python Debugger.
- Create a Python Virtual Environment, press Ctrl+Shift+P and search for the option: Python: Create Environment
    - Create a .env environment.
    - When asked about which Python version to select, choose the latest version 3.12.1.
    - When asked if you wish to install requirements.txt. Select the option and let it install. This will install every      library necessary for the project.
    - Check in VsCode terminal or in the interpreter section, that you are using the .venv and not the global interpreter.

- If you install a new library that it is necessary for the project, please run "pip freeze > requirements.txt", this will update the file.
    - If you don't have all of the libraries in requirements.txt run "pip install -r requirements.txt" command.


-After this, the you should be able to run the code and test everything in your local host.

**COMMENTS**

- The functions in the branch are an example, so everyone can understand the functionality of them.

**LINKS**

https://www.python.org/downloads/

https://marketplace.visualstudio.com/items?itemName=ms-python.python

https://flask.palletsprojects.com/en/3.0.x/

https://www.postgresql.org/docs/current/

https://www.postgresqltutorial.com/

https://www.restapitutorial.com/lessons/httpmethods.html

https://www.psycopg.org/docs/index.html

https://flask-cors.corydolphin.com/en/latest/api.html

**Comment by Javi510348** [comment]
Change from the code from Pyhon to NodeJs.

**Comment by Javi510348** [comment]
File Structure:

backend
|
|
-config (Responsible of storing database information)
-controller (Manages the data received from the database)
-dao (pattern that provides an abstract interface to the database)

Instructions for Development:

    Make sure that you have the latest version of NodeJs (Follow the main README file for further instructions).
    Run npm install, so you can install the latest dependencies for the project
    index.js is responsible of managing all of the routes
    Install ThunderClient extension in Vscode so you can test all of the API routes. For example: POST, PUT
    Run the project by using npm start

If you installed the virtual environment for Python, you can delete the environment folder in vscode.*

COMMENTS

The functions in the branch are an example, so everyone can understand the functionality of them.

If you have any questions, please let me know

LINKS

https://nodejs.org/en

https://marketplace.visualstudio.com/items?itemName=rangav.vscode-thunder-client

https://www.postgresql.org/docs/current/

https://www.postgresqltutorial.com/

https://www.restapitutorial.com/lessons/httpmethods.html

https://node-postgres.com/

**Comment by Javi510348** [comment]
Everything has been changed from Python to NodeJs.
