### ISSUE TITLE
Milestone 3 Presentation Attribution - Web Management Team 📱

### ISSUE THREAD

**Issue by rukitoyordan** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#263]
### Attribution
The purpose of this task is to present organized and detailed information of the achievements of the Website Management team towards the proper documentation and development on the **_Milestone 3 Presentation_**.

This will be updated to portray visibility in the documentation progression and results.

The assigned sections will be shown in further comments and will be discussed by Team Leaders alongside their Developers.

**Deadline: Fri, April 26 2024 @1800** 🚨

**Comment by smbv** [comment]
**My M3 contribution:**

Call to action buttons
- Enhanced user engagement and interaction on the homepage by strategically placing call-to-action buttons. These buttons will serve as essential entry points for users, encouraging them to take specific actions related to adoption, donation, volunteering, and learning more about the adoption process

**Comment by Adriana-Isabel** [comment]
_My M3 contribution:_

### **Featured Pets**

Highlights distinct categories of pets available for adoption. Each category emphasizes a different aspect of the pets, such as their waiting time, special needs, staff favorites, and new arrivals, showcasing the diversity and individuality of the animals awaiting for their adoption.

- Animals Waiting the Longest: These are the pets who have been patiently waiting for adoption, sometimes overlooked. 

- Animals with Special Needs: Every animal deserves a chance at a happy life, regardless of any special requirements they may have. Here, we introduce some of our special-needs pets, each with their own remarkable resilience and capacity for love.

- "Staff Picks": Pets that have captured the hearts of the staff members with their unique personalities. 

- New Arrivals: Fresh faces join shelters regularly, each one bringing their own bundle of excitement and anticipation. Meet the latest additions, ready to embark on new adventures with loving caregivers.
