### ISSUE TITLE
Donation Page

### ISSUE THREAD

**Issue by AlexisTraversoPR** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#271]
Objective:
 - The objective of this task is to have a functioning page for donations where a QR code linked to a ATH móvil number will be displayed.

Task description:
 - This task involves the creation of a new donation page accessible from the homepage. It will add functionality to the website as this the type of work that this website aims to aid usually benefits from donations and contributions greatly.

Implementation:
 - A ejs view page will be created and linked to the homepage. It should be accessible from the homepage either from a new donation button or from the donation information box already present in the homepage. The page will have messages describing why donations are helpful and contain a QR code linked to a number that has ATH movil as it is compatible with the target audience.

Subtasks:
 - Create a new page. Keep page design consistent with the rest of the page. 

Testing and Debugging:
 - Ensure QR code functions correctly. Test that the you can go from home page to donation page without breaking the other parts of the code.

Deadline: April26 at midnight, as milestone ends.

**Comment by Alejandro-DeJesus** [comment]
Task is implemented feature complete
