### ISSUE TITLE
Project Hosting

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#32]
Once we have some routes running in the project, we should start hosting our project. Currently,  my candidate for the hosting of the project is Render since it has great compatibility with python. Another reason for this selection is that Render will allow us to do free hosting.

**COMMENTS**

- If someone has a recommendation for the hosting service, please let us know. Any suggestion will be appreciated.

https://docs.render.com/

https://docs.render.com/deploy-flask

**Comment by rukitoyordan** [comment]
@Javi510348, do you have a status on this? I need to know if you wish to keep this for Milestone 3 or be moved to the Product backlog.

**Comment by Javi510348** [comment]
Considering the importance of other tasks, we should move to the product backlog.
