### ISSUE TITLE
Define the Human Profile

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#33]
Define in the backend the properties that the human profiles will hold:

1. Name
2. User ID - Allows for 
3. Age
4. Location
5. Previous Pets
6. Foster (yes/no)

Among others that will result necessary. 

Communicate with the pet profiles team to ensure shared keys are defined.

**Comment by evnd04** [comment]
This info should serve as the basis for your database table, remember to do some sort of hashing for any sensitive information like users and passwords for security reasons like the professor discussed.
