### ISSUE TITLE
Research for User Friendly Design

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#35]
Conducting research for user-friendly design is essential for creating an adoption app that effectively meets the needs of the users and enhances their experience.

1. **Understanding User Needs:**  Understand the needs, preferences, and behaviors of the target users. This knowledge is crucial for designing an interface that caters to their requirements and enhances their experience.

2. **Competitive Analysis:** Researching existing adoption apps and similar platforms can provide valuable insights into industry trends, best practices, and areas for differentiation. Analyzing competitors' strengths and weaknesses can inform the design decisions and help  create a more competitive product.

**Comment by evnd04** [comment]
As stated by @smbv this is already an issue in the product backlog

**Comment by Adriana-Isabel** [comment]
### **Companies used for research:** 
The Human Society of the United States: https://www.humanesociety.org/
Pet Finder: https://www.petfinder.com/
Best Friends Save Them All: https://bestfriends.org/
American Society for the Prevention of Cruelty to Animals: https://www.aspca.org/



### **What do all of these companies’ websites have in common that make them likeable by the target user?**

**Pet Listings:** All of these websites provide listings of adoptable pets, including information about each animal such as breed, age, gender, temperament, and photos.

**Search and Filtering Tools:** They typically offer search and filtering tools that allow users to narrow down their options based on criteria such as species, breed, size, age, location, and other preferences.

**Adoption Process Information:** Information about the adoption process, including requirements, fees, and application procedures, is commonly provided to help potential adopters understand what to expect.

**Education and Resources**: These websites often offer educational resources and information about responsible pet ownership, including topics such as pet care, training, behavior, and health.

**Support for Shelters and Rescues:** Many of these websites support animal shelters and rescue organizations by providing them with a platform to showcase their adoptable pets and reach potential adopters.

**Community Engagement:** They may facilitate community engagement through features such as user reviews, testimonials, success stories, forums, and social media integration.

**Donation Opportunities:** Most of these websites offer opportunities for users to donate to support their mission and programs, whether through one-time donations, recurring donations, or sponsorship programs.

**Volunteer and Foster Opportunities:** Some websites may also provide information about volunteering, fostering, or other ways to get involved in animal rescue and welfare efforts.



### **What are the needs, preferences, and behaviors of the target users?**

**_Potential Adopters:_**
**Needs:** Potential adopters are looking for a compatible pet to add to their family. They may have specific preferences regarding the pet's breed, size, age, temperament, and compatibility with their lifestyle.

**Preferences:** Potential adopters may prefer an adoption process that is convenient, transparent, and supportive. They may also value features such as detailed pet profiles, easy communication with shelters or foster caregivers, and opportunities to learn about pet care.

**Behaviors:** Potential adopters may spend time researching different adoption options online, browsing through pet listings, attending adoption events, and interacting with animals in person before making a decision.

**_Donors and Supporters:_**
**Needs:** Donors and supporters are interested in contributing to the organization's mission of animal rescue and adoption. They may want to make monetary donations, sponsor specific animals, or purchase merchandise to support the cause.

**Preferences:** Donors and supporters may prefer a platform that makes it easy to donate securely, learn about the organization's impact, and stay updated on upcoming events or fundraising campaigns.

**Behaviors:** Donors and supporters may visit the adoption app to make donations, browse available merchandise, read success stories, and share information about the organization with their networks.
