### ISSUE TITLE
Research and design the user profile interface

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#37]
1. Conduct research on existing websites
-Explore a variety of pet adoption websites to understand their functionalities, user experience, and design aesthetics.
-Analyze the layout, navigation, and visual elements used in these websites to identify common design trends and best practices.

2. Design a concept of the user profiles tab
-Identify interactive elements and functionalities required for the website, such as form validation, image sliders, dropdown menus, and modal dialogs.
-Develop a consistent design system based on typography, color palette, spacing, and visual elements.

**Comment by rukitoyordan** [comment]
@Angel-Rosado, was this done? Please let me know so that we can either have it moved to Milestone #2 or marked as completed in the past milestone!

**Comment by rukitoyordan** [comment]
@Angel-Rosado reminder on answering this please!

**Comment by Angel-Rosado** [comment]
Done
