### ISSUE TITLE
Determine shared keys between pet profiles and human profiles

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#38]
Research and determine the keys that the pet profiles and the human profiles will share. 

Example:
user_id - to connect humans with respective pets

Discuss research with the pet profiles team.

**Comment by evnd04** [comment]
Do this task ASAP since its the base of the work you will all be doing.

**Comment by rukitoyordan** [comment]
@Angel-Rosado, please notify me if the status of this ASAP.

**Comment by Angel-Rosado** [comment]
Done
