### ISSUE TITLE
Home Page Optimization for Pet Adoption App

### ISSUE THREAD

**Issue by Adriana-Isabel** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#39]
In this task, we aim to enhance the home page to create a compelling and user-friendly experience for potential adopters. By optimizing navigation, search functionality, and featured content, we aim to promote engagement and facilitate the adoption process effectively.

 
**1. Header**
* Include your app's logo and a clear menu with icons for:
    *  Browse Animals
    * ️ Adoption Events
    *  My Matches
    *  Messages
    *  Settings

**2. Hero Section**
* Captivating image/slideshow of happy animals & successful adoptions.
* Welcoming message emphasizing app's mission & finding your "perfect match." Keywords: love, forever home, second chance.

**(3. Search & Filter Options)**
* Prominent search & filter options to narrow down animal searches.
* Filter by:
    * Species
    * Breed
    * Sex
    * Age
    * Size
    * Location
    * Temperament
    * Special Needs (optional)

**4. Featured Animals**
* Highlight adoptable animals with high-quality photos & compelling descriptions.
* Include a mix of:
    * Animals waiting the longest
    * Animals with special needs
    * "Staff picks"
    * Vaccines
    * New arrivals

**5. Swipe Feature**
* Prominent swipe feature for intuitive browsing.
* Clear visual cues & instructions on how to use the swipe function (e.g., right for interested, left for pass).

**(6. Upcoming Events)**
* Upcoming adoption events, pet fairs, or fundraisers in the user's area.
* Include details like:
    * Date
    * Time
    * Location
    * Clear call-to-action button (e.g., RSVP, Learn More)

**(7. Testimonials & Success Stories)**
* Showcase testimonials or success stories from happy adopters.
* Photos of adopted pets with families & brief, heartwarming anecdotes about their adoption journey.

**(8. Call to Action Buttons)**
* Prominent call-to-action buttons throughout the homepage:
    * "Find Your Match"
    * "Donate Now"
    * "Volunteer"
    * "Learn More" (about adoption process)

**(9. Footer)**
* Links to important pages:
    * About Us
    * Contact Us
    * FAQs
    * Terms of Service
    * Privacy Policy
* Social media icons to connect with users on various platforms.

**Additional Tips:**
* Consistent, visually appealing design reflecting your app's brand identity.
* High-quality images & videos showcasing animals & your organization's work.
* Concise & easy-to-read content on mobile devices.
* Data-driven insights to optimize user experience & feature placement.
* Regularly update content with fresh animals, events, and stories.

**Comment by evnd04** [comment]
I believe this is a huge task that can be allocated to multiple students, so I believe a split is necessary, but the task is well written and explains all the necessary aspects of each feature. Well done!

**Comment by evnd04** [comment]
It could also be split with multiple teams.

**Comment by Adriana-Isabel** [comment]
I've incorporated the researched specifications in a mockup website to enhance the user experience and promote engagement on our home page. (The Hero Section has stories of sports, that's an error. There goes the stories of the rescued and adopted animals.)

https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/7638b1eb-bad6-4f52-999e-1ea12cea921f

**Comment by rukitoyordan** [comment]
Thank you all for the well organized split. Regardless if these are individually done by the end of the Milestone, make sure to mark this as done since the split has been done! @Adriana-Isabel
