### ISSUE TITLE
Emails from people who will be responsible of database tables

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#40]
I need the emails from the people who are going to work with the database tables, so I can add you to the project in Supabase. We need to set this up as fast as possible. Without the tables we may be unable to advance with some features.

Due Date: 2/16/2024

**Comment by Angel-Rosado** [comment]
For Human Profiles - angel.rosado13@upr.edu

**Comment by Javi510348** [comment]
You should receive an email with the invitation. If the invitation link expires or something, please let me know

**Comment by Javi510348** [comment]
@Alejandro-DeJesus If you can, please change all of the colums names to lowercase. Use lowercase and underscore only since PostgreSQL could have problem when working with queries and uppercase letters.

**Comment by Alejandro-DeJesus** [comment]
> @Alejandro-DeJesus If you can, please change all of the colums names to lowercase. Use lowercase and underscore only since PostgreSQL could have problem when working with queries and uppercase letters.

thank you for letting me know, just fixed it!

**Comment by RaquelQuinones** [comment]
@Javi510348 Hi, can also get the invite for the database tables? My email is raquel.quinones7@upr.edu

**Comment by Javi510348** [comment]
@RaquelQuinones Sent you the invitation via email. If you need anything else, please let me know.

**Comment by Alej24** [comment]
For Pet Listings - alejandro.rivera24@upr.edu

**Comment by Javi510348** [comment]
@Alej24 Sent you the invitation via email. If you need anything else, please let me know.
