### ISSUE TITLE
Create a Visual Mood Board - Website Creation

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#42]
**Description:**
Each team member is assigned to create a mood board to initiate the visualization of our website's design. The mood board is an open canvas for your ideas, color palettes, pictures inspired by other websites, and any elements that reflect your vision for the project. In case you are not familiar with mood boards, I will leave a few resources and examples attached here. Let your creativity flow! Once completed, share the finished mood boards in the comments section. Feel free to use any preferred platform for this task. You are not bound to use the suggested ones.

**Deadline:**
Aim to complete this task by February 19

**Platform Suggestions:**
1. **[Canva:](https://www.canva.com/)**  
- Graphic design platform suitable for both beginners and experienced designers. It offers a wide range of templates and easy collaboration features.

2. **[Figma:](https://www.figma.com/)** 
- Collaborative design tool that has gained popularity for its powerful features and emphasis on real-time collaboration. 

3. **[Pinterest:](https://www.pinterest.com/)**
- Not a design platform but its a great source for collecting inspiration. You can create a board and gather images that resonate with your design vision.

4. **[Adobe Spark:](https://spark.adobe.com/)**
- Web-based design tool by Adobe, offering features to create graphics, web pages, and video stories. 

5. **[Miro:](https://miro.com/)** 
- Collaborative online whiteboard platform suitable for creating mood boards.

**Resources:**

1. [Milanote - Website Design Moodboard Guide](https://milanote.com/guide/website-design-moodboard)
- provides a comprehensive guide on creating a moodboard specifically tailored for website design. Follow the steps outlined in this guide to effectively visualize your ideas.

2. [YouTube - How to Create a Moodboard](https://youtu.be/1A-tepzfhJw?si=UrHL-5apgO6Cnzxl)
- This video tutorial on YouTube walks you through the process of creating a mood board. Gain insights and practical tips to enhance your mood boarding skills.

3. [YouTube - Designing a Mood board in Canva](https://youtu.be/ERrDs9VSOq0?si=-4yh5qvyUTkUJqv5)
- Explore this video tutorial on designing a mood board using Canva. Learn how to utilize the features of Canva to bring your creative ideas to life.

4. [YouTube - Mood board Design Process in Figma](https://youtu.be/O7YJrT0s3QM?si=pFPCTnQhNyYVTSAA)
- This video delves into the overall design process of creating a mood board using Figma. Understand the key elements and steps involved in crafting an effective mood board for your project.

5. [Conceptboard - Mood Board Free Template Guide](https://conceptboard.com/blog/mood-board-free-template-guide-examples/)
- Access free templates and gain insights into creating mood boards effectively. This link provides valuable information, examples, and templates to streamline your mood board creation process. 

Examples:

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/d30da1ec-f86d-4bbb-8167-a9803db3444f)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/677e0369-2ccc-4543-8d00-b1a809d19654)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/9f5270e7-c897-40ae-978d-5aa18b1c04e9)

**Comment by Adriana-Isabel** [comment]
![Screenshot 2024-02-15 201755](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/29364179-71de-4c54-8d4c-d48dcb7d356d)

**Comment by GiovanniMaysonet** [comment]
![moodboard](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/d07433e2-cf0f-42df-a146-b04839d96f97)

**Comment by smbv** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/3b85df16-0062-4c86-8907-2e93e45fe32e)

**Comment by christianperez42** [comment]
![RUMAR ANIMAL RESCUE SERVICE](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/70546091/5503a968-e0f6-447e-a4e2-3e669647822a)
