### ISSUE TITLE
Create a Mockup - Website Creation

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#43]
**Description:**
- Each team member is assigned to create a distinct mockup for the landing page of the website. This individualized approach allows for diverse design perspectives. This task lays the groundwork for a more concrete representation of the website's structure and layout. In case you are not familiar with mockups, I will leave a few resources and examples attached here. Use the platform of your choice, considering the suggested options or exploring alternatives.
Once you're done, post your mockup in the comments. Have fun!

**Deadline:** 
- Aim to complete this task by February 23.

**Platform Suggestions:**

1. **[Moqups](https://moqups.com/):**
   - Ideal for beginners, Moqups provides an intuitive platform for creating wireframes and mockups with ease.

2. **[Figma](https://www.figma.com/):**
   - A free and versatile option for creating mockups, Figma allows collaborative design with real-time updates.

3. **[UXPin](https://www.uxpin.com/):**
   - Tailored for handing off design documentation to developers, UXPin streamlines the collaboration process.

4. **[Mockflow](https://www.mockflow.com/):**
   - Offering end-to-end project management, Mockflow is a comprehensive solution for mockups and design.

5. **[Justinmind](https://www.justinmind.com/):**
   - Create interactive mockups with Justinmind, empowering you to visualize user experiences dynamically.

6. **[Uizard](https://uizard.io/):**
   - An AI-assisted tool, Uizard accelerates the wireframing and mockup process by providing intelligent design suggestions.

**Resources:**

1. [Wireframing Basics (Flux Academy)](https://www.youtube.com/watch?v=HZuk6Wkx_Eg&ab_channel=FluxAcademy)
- A comprehensive guide to understanding the fundamentals of wireframing. Gain insights into key concepts and best practices.

2. [Web Development Crash Course (freeCodeCamp.org)](https://www.youtube.com/watch?v=pN92rnO_n5U&ab_channel=freeCodeCamp.org)
- A crash course in web development covering essential concepts. 

3. [Wireframing Techniques (Flux Academy)](https://www.youtube.com/watch?v=x3Yno9VUYBY&ab_channel=FluxAcademy)
- Learn how to create effective wireframes for website projects.

4. [Home Page Layouts (The Website Architect)](https://www.youtube.com/watch?v=g0db5kA4BfQ&ab_channel=TheWebsiteArchitect)
- This tutorial caters to beginners, offering a step-by-step guide to home page layouts.

5. [Mockup Tutorial (freeCodeCamp.org)](https://www.youtube.com/watch?v=c9Wg6Cb_YlU&ab_channel=freeCodeCamp.org)
- Guide to wireframing, mockups and website design. 

Examples:

![WhatsApp Image 2024-02-15 at 01 01 45_c24b69f5](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/754c4c14-3c99-483d-a70a-a22170789448)

![WhatsApp Image 2024-02-15 at 01 01 44_bab4cb8a](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/206cb442-4dbd-4058-90c7-7f2a4444c406)

![WhatsApp Image 2024-02-15 at 01 01 44_04571386](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/9ca1393a-edb7-430a-a1b5-96fa21379495)

**Comment by smbv** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/116372c6-e916-4770-ba93-ea51db962902)

**Comment by christianperez42** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/70546091/7742d3bc-994f-45d7-b3ef-6d5c43ac69c8)

**Comment by GiovanniMaysonet** [comment]
Here is my mockup

https://app.moqups.com/ZkgSy7aUKwqLnVbFBnUnRm5iuW7PL7B7/view/page/a8b49fd9f
