### ISSUE TITLE
Create a Wireframe - Website Creation

### ISSUE THREAD

**Issue by smbv** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#47]
**Description:**
- Each team member is assigned to create a distinct wireframe for the landing page of the website. This individualized approach allows for diverse design perspectives. This task helps define the website's structure and layout. In case you are not familiar with wireframing, I will leave a few resources and examples attached here. Use the platform of your choice, considering the suggested options or exploring alternatives. Once you're done, post your wireframe in the comments. 

**Deadline:** 
- Aim to complete this task by February 21.

**Platform Suggestions:**

1. **[Balsamiq](https://balsamiq.com/):**
   - Known for its simplicity, Balsamiq is a user-friendly tool that allows for quick and effective wireframing.

2. **[Axure RP](https://www.axure.com/):**
   - Axure RP is a powerful tool that enables not only wireframing but also prototyping, making it a comprehensive solution for your design needs.

3. **[Sketch](https://www.sketch.com/):**
   - Popular among designers, Sketch offers a flexible platform for wireframing and designing interfaces.

4. **[Adobe XD](https://www.adobe.com/products/xd.html):**
   - Adobe XD provides a seamless design and prototyping experience, making it an excellent choice for creating wireframes.

5. **[Wireframe.cc](https://wireframe.cc/):**
   - A straightforward and easy-to-use online tool, Wireframe.cc focuses on the essentials, allowing you to quickly sketch out your ideas.

6. **[InVision](https://www.invisionapp.com/):**
   - InVision not only facilitates wireframing but also offers collaboration and prototyping features for a more holistic design process.

**Resources:**

1. [Wireframing Basics (Butter Academy)](https://www.youtube.com/watch?v=6t_dYhXyYjI&ab_channel=ButterAcademy)
   - Guide to understanding the fundamentals of wireframing. 

2. [Figma Wireframing (CareerFoundry)](https://www.youtube.com/watch?v=qpH7-KFWZRI&ab_channel=CareerFoundry)
   - Wireframing basics in Figma. Gain insights into key concepts and best practices.
   
 **Examples:**
   
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/978a5ad0-da42-40e3-92de-d791ffae6d27)

![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/4ff6edeb-4766-48ad-bd5b-8bd811e692d3)

**Comment by Adriana-Isabel** [comment]
https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/f7d60419-9ec7-4315-bbac-f6aaa469d8bc

**Comment by Adriana-Isabel** [comment]
![Screenshot 2024-02-18 224346](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/3847b193-5c94-4c17-8e28-b0f907699a7f)
![Screenshot 2024-02-18 223115](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/86ecda3e-f387-44f9-b505-70f0e616a9ed)
![Screenshot 2024-02-18 223128](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94401170/cab1cefe-f4ad-42a2-9c44-cc5bcb4a8361)

**Comment by smbv** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/82616129/a6890bd2-5f14-4c6b-a0d0-2373846c57a6)

**Comment by christianperez42** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/70546091/141e24c7-f0ee-42e5-b056-06740f34d2fa)

**Comment by GiovanniMaysonet** [comment]
![image](https://github.com/uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp/assets/94716916/37618f5a-3d12-46c3-bd43-64b8f482af18)

Here is the wireframe.

**Comment by rukitoyordan** [comment]
@smbv seeing that the wireframes are here posted, is this task done then?
