### ISSUE TITLE
Login/sign-up Prototype 

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#48]
Create a base code to implement sign-in/login features

due date by 2/19/2024

**Comment by 1uismar33r0** [comment]
Worked in the backend hash verify of the password and Query for Login

**Comment by jhsanchez26** [comment]
Worked on the frontend to implement a rough design of the login and signup pages. Created links from the home screen to each page and a link from login to signup in the case that a user attempted to log in but did not have an account.

**Comment by Javi510348** [comment]
The basic prototype for login and signup has been completed by all team members, the issue will be closed.

If anyone has any questions, please let us know
