### ISSUE TITLE
database fetch for human profiles

### ISSUE THREAD

**Issue by rafa-quiles** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#54]
Ensure that the proper query is set and working to fetch the data that will be displayed in the front end based on the human profiles. This involves:

- Understanding the query format.

- Making sure the code manages the data properly and that it can be displayed on the front end.

**Comment by evnd04** [comment]
Add tags

**Comment by evnd04** [comment]
Add a little more to the explanation of the task.

**Comment by rukitoyordan** [comment]
@rafa-quiles

**Comment by Angel-Rosado** [comment]
Completed
