### ISSUE TITLE
Investigate and Troubleshoot incompatability with Live Server Extension

### ISSUE THREAD

**Issue by GiovanniMaysonet** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#55]
1. **Check for Updates**: Ensure that both Visual Studio Code and the Live Server extension are up to date. Sometimes, compatibility issues are resolved in newer versions of extensions.

2. **Review Extension Documentation**: Look for documentation or release notes for the Live Server extension to see if there are any mentions of virtual workspace support or known issues related to it. This might provide insight into whether the extension is designed to work with virtual workspaces or not.

3. **Alternative Extensions**: If the Live Server extension doesn't fully support virtual workspaces, consider using alternative extensions that do. There are several similar extensions available in the Visual Studio Code Marketplace that might offer the functionality you need without compatibility issues.

4. **Reach Out to Developer Community**: Reach out to the developer community for the Live Server extension. This could include checking forums, GitHub issues, or other communication channels where users and developers discuss extension-related problems and solutions.

5. **Report the Issue**: If you confirm that the extension doesn't support virtual workspaces or if you believe it's a bug, report the issue to the extension developer through their preferred channels (such as GitHub issues or a support forum).

**Comment by evnd04** [comment]
Well documented, good job

**Comment by GiovanniMaysonet** [comment]
After researching and going through every step of the task my team has concluded that its best we use the terminal as an alternative to the live server function. The author's github is unresponsive. No similar issues have been addressed or offered a solution. It would be impractical and time consuming to continue trying to fix or force live server to work.

I leave this task as completed and closed.
