### ISSUE TITLE
Fetch data from pets data tables

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#57]
Write code in the backend so that the data from the pets data table can be accessed.

**Comment by evnd04** [comment]
Add more information about the task to be done before approval.

**Comment by evnd04** [comment]
Add more to be approved.

**Comment by rukitoyordan** [comment]
@Alejandro-DeJesus why was this issue closed?

**Comment by Alejandro-DeJesus** [comment]
> @Alejandro-DeJesus why was this issue closed?
> 

There was an already approved, similar issue. I've closed this one since they had a lot of overlap.
