### ISSUE TITLE
Create front end template for pet profiles

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#58]
Create a front end file that can be used a template for any Pet's profile. The file should not have any specific data and be versatile enough that any pet can use it to display it's associated data.

**Comment by evnd04** [comment]
Handy tool for the profiles to have a consistent template, add a description of what the template might hold and maybe a brief description of what it would look like.

**Comment by Alejandro-DeJesus** [comment]
For current purposes the template will be primarily functional and void of most stylistic decisions. The template serves to indicate what data will be displayed where.
template would follow something akin to:

Name
gender
(image of pet)
species
age
personality

**Comment by AlexisTraversoPR** [comment]
The basic front end template for displaying the pet and its information has been made
