### ISSUE TITLE
Pet Listings Filtering by Size

### ISSUE THREAD

**Issue by diegorobles2** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#62]
Create a feature for pet listing platform that allows users to filter pets based on their size. This feature enables the user to find pets that suit their living space and lifestyle preferences more effectively. Users should be able to select from various size options and view only pets that match their chosen criteria.

**Comment by evnd04** [comment]
Very necessary feature due to the target audience being college students who might have stricter requirements for pets.
