### ISSUE TITLE
Local Host creation request/approval,  Human Profiles 

### ISSUE THREAD

**Issue by ErickCruz4** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#63]
The idea is to create a localhost, also known as loopback address, refers to the local computer itself. When you set up a localhost, you're essentially creating a server environment on your own machine that can host web pages or web applications for testing or development purposes without needing to be connected to the internet. 
2 man task.   
@ErickCruz4 
@HectorSepul

**Comment by Angel-Rosado** [comment]
Done
