### ISSUE TITLE
Cycling Through Pet Listings

### ISSUE THREAD

**Issue by Alej24** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#65]
Have the pet listing tab cycle horizontally and automatically every few seconds with each tab focusing on a different characteristic of the featured animals such as the species, or the breed, or the personality, etc.  This feature would allow more pet listings to be shown in an organized manner while not occupying such a large space.

**Comment by evnd04** [comment]
What do you mean by cycle? It's definitely a necessary feature but what does it mean to cycle automatically?

**Comment by Alej24** [comment]
Let's say that there are 5 featured listings, and instead of showing all 5 of them at the same time, it could show 1 listing at a time and then shift onto the next after a certain amount of seconds and continuously do that, which could give the pet listings area a more organized look and allow more focus to one listing at a time.

**Comment by evnd04** [comment]
It would look nice but what would a featured listing be? Like a daily spotlight to a certain pet, if so how would these be chosen if the system is full of pets? Or will this be basically an automatic cycle through all the pets in the system?

**Comment by evnd04** [comment]
Please provide a more complete overview of the feature to be approved.

**Comment by Alej24** [comment]
> It would look nice but what would a featured listing be? Like a daily spotlight to a certain pet, if so how would these be chosen if the system is full of pets? Or will this be basically an automatic cycle through all the pets in the system?

The featured listings would be chosen at random from all the pets in the system.

**Comment by evnd04** [comment]
Is this still being worked on?

**Comment by rukitoyordan** [comment]
@Alej24, please answer or the task will be denied for further development in 24 hours.

**Comment by Alej24** [comment]
My apologies for the delay but the task is not being worked on.
