### ISSUE TITLE
terminology, events, actions, and behaviors documentation

### ISSUE THREAD

**Issue by rafa-quiles** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#68]
document  the  terminology of the project and the events, actions, and behaviors of the domain

**Comment by rafa-quiles** [comment]
terminology

  • pet: animal, usually a cat or dog that are being take care of by a 
  person.

  • adopt: process where a person goes to the shelter and takes a pet 		
  back to their home to take care of it

  • shelter: organization that rescues and takes care of animals until
  a person adopts them

  • adoption form: document that a person fills out to determine if they 
  are suitable for adoption

  • foster: people that take care of pets temporarily until the pet is 	
  adopted

Actions
  • pet profile creation: creatin a profile for a pet by inputting its 
  information into the system

  • filling adoption form: the person interested in adopting fills the    
  for wit their information

  • registering: The act of creating an account and making a profile by  
  giving the necessary information for the profile
  (email, phone number, location, age, gender)

  • verification: making sure than a user is fulfills the conditions to  
  be able to take care of a pet

  • pick up: the user that has been approved and selected a pet, goes to 
  get the pet and take it home


Events
  • pet added: when a pet is registered to the system.

  • selection: when a user selects the pet they wish to adopt.

  • form submission: when a user submits the adoption form for it to be 
  reviewed.

  • approval: when a user is determined to be capable of taking care of 
  a pet.

behaviors

  • adopting: series of events and actions taken by the association and  
  the user to adopt a pet (registration, filling the form, selecting, 
  approval, pick up).

  • fostering: a member of the organization takes care of pet  
  temporarily until the pet is adopted.

**Comment by rafa-quiles** [comment]
this is my addition it can now be added to the documentation

**Comment by evnd04** [comment]
Due to your wok with the terminology and your leader working on the domain rough sketch can you also do ◊ 2.1.3 domain terminology in relation to domain rough sketch, ill add points that reflects this extra work

**Comment by rafa-quiles** [comment]
i didn't write anything for that section since i understood that it wasn't a part to be written, instead instructions from the professor on how to approach definitions.

if you want me to write something please clarify, because i don't understand what the professor wants in that section

**Comment by Adriana-Isabel** [comment]
I can do the 2.1.3 part.
