### ISSUE TITLE
Pet Listings Documentation

### ISSUE THREAD

**Issue by Alej24** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#69]
Documentation on any of the work the pet listings team has done.

**Comment by evnd04** [comment]
This should be included in any part that specifically envolves the work done in the project in the documentation such as

2.2.3 domain requirements
2.2.4 interface requirements
2.2.5 machine requirements
 2.1.6 function signatures

and most importantly the entire 2.3 implementation section just so you know where to work

**Comment by evnd04** [comment]
When possible add info on which parts your team will work on
