### ISSUE TITLE
Pet Listings Documentation 

### ISSUE THREAD

**Issue by JohnSantiagoRuiz** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#72]
Pet listings will document parts 2.1.6 which is function signatures, 2.2.4 which would be interface requirements and 2.2.5 which would cover machine requirements.

**Comment by rukitoyordan** [comment]
Let me know who is also working on this so that they can be assigned to this task! @JohnSantiagoRuiz j
