### ISSUE TITLE
Additional boxes for signup

### ISSUE THREAD

**Issue by Saul-Caban-UPRM** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#83]
Add email, first name, last name, email, gender, location and other boxes for signup.  Create an input filed for names, email, location and drop down selection for gender section in the signup.ejs file

**Comment by evnd04** [comment]
Approved but add info on the possible implementation.

**Comment by Saul-Caban-UPRM** [comment]
Okay I edited the description with additional informaton

**Comment by Javi510348** [comment]
The issue is going to be closed since it has been completed.

If anyone has any questions, please let us know.
