### ISSUE TITLE
Implement a faculty member tab

### ISSUE THREAD

**Issue by Angel-Rosado** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#93]
Add a tab page to the website which will display the list of users in the database that are members of RUMAR and function as point of contacts for the users to reach out to:

- Grab the user data of the faculty members
- Create a page to display the list of faculty members
- Create the list of faculty members

**Comment by evnd04** [comment]
Sounds good, what faculty members would be included? Does faculty include the student members of the association or fosters? This should be defined, preferably here on the issue.

**Comment by Angel-Rosado** [comment]
Yes, task states faculty as members of RUMAR that the users can reach out to, such as members of the association in the database.
