### ISSUE TITLE
Avoid adding duplicate users to the database

### ISSUE THREAD

**Issue by Javi510348** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#94]
We need to avoid the situation in which a user could create an account with an email and/or username that already exists in the database.

Two queries will be created in which one of them is going to check if the username already exist in the database and the other query will check if the email is already in the database.

If the data provided already exists, it will let the user know that the email or username has been already used for another account.  We are going to try to implement this message with a pop up window if it's possible

Due Date: 03/05/2024

**Comment by evnd04** [comment]
Provide a minimal overview of how the implementation might work, I'm guessing when the user makes the account its saved into the database, and if the user tries to make a new account it first searches the db to ensure that info is not a duplicate and rejects if it is.

**Comment by Javi510348** [comment]
@evnd04  More details have been added with how it should be implemented.

**Comment by Javi510348** [comment]
@evnd04 Should I do the Pop Up part as a separate feature or should I try to have everything in the same in the same issue.?

**Comment by evnd04** [comment]
If you think it's a dense enough task to be its own issue, I suggest you divide it with another member of your team. If it is a trivial task that takes little to no effort keep it in the same issue.
