### ISSUE TITLE
Survey for team member availability

### ISSUE THREAD

**Issue by Alejandro-DeJesus** [uprm-inso4101-2023-2024-s2/semester-project-rumaradoptionapp#96]
Please click on the following link and mark the hours you are available during the week:
https://www.when2meet.com/?23924280-SSAJD

This will be used to coordinate future team meetings

deadline: March 3, 2024, 23:59pm

**Comment by Alejandro-DeJesus** [comment]
Link for Per Interfaces chat: https://chat.whatsapp.com/CNySafZxr5Q853gFrFSuKz

**Comment by rukitoyordan** [comment]
> Link for Pet Interfaces chat: https://chat.whatsapp.com/CNySafZxr5Q853gFrFSuKz

This is good! make sure to also use the Discord channels we made for you too!
